window.AykaApostila=(function(){function go(id){const el=document.getElementById(id);if(el) el.scrollIntoView({behavior:'smooth',block:'start'});} function toggleAnswer(id){const el=document.getElementById(id);if(el) el.classList.toggle('show');}
function renderMeta(data){const map={coverIcon:data.coverIcon,coverTitle:data.coverTitle,coverSubtitle:data.coverSubtitle,coverNote:data.coverNote,footerInfo:data.footerText||`${data.coverTitle} • Projeto Ayka`}; Object.entries(map).forEach(([id,val])=>{const el=document.getElementById(id); if(el) el.innerHTML = val || '';}); const pills=document.getElementById('coverPills'); if(pills) pills.innerHTML=(data.pills||[]).map(item=>`<span class="pill">${item}</span>`).join(''); const chips=document.getElementById('scienceBar'); if(chips) chips.innerHTML=(data.chips||[]).map(item=>`<div class="science-chip">${item}</div>`).join('');}
function renderVideos(data){const grid=document.getElementById('videosGrid'); if(!grid) return; grid.innerHTML=(data.videos||[]).map(video=>`<div class="video-card"><h4>${video.title}</h4><p>${video.description}</p><a class="video-link" href="${video.url}" target="_blank" rel="noopener noreferrer">Abrir busca</a></div>`).join('');}
function initQuiz(data){const quizData=data.quizData||[]; if(!quizData.length) return; let quizIndex=0,quizScore=0,answered=false; function renderQuiz(){answered=false; const item=quizData[quizIndex]; document.getElementById('quizQuestion').textContent=item.q; document.getElementById('quizScore').textContent=`Questão ${quizIndex+1} de ${quizData.length}`; document.getElementById('quizBar').style.width=`${(quizIndex/quizData.length)*100}%`; document.getElementById('quizFeedback').textContent=''; document.getElementById('quizFeedback').style.color='#ffffff'; document.getElementById('quizNext').disabled=true; const options=document.getElementById('quizOptions'); options.innerHTML=''; item.opts.forEach((opt,index)=>{const button=document.createElement('button'); button.className='quiz-option'; button.textContent=opt; button.onclick=()=>answerQuiz(index); options.appendChild(button);});}
function answerQuiz(selected){if(answered) return; answered=true; const item=quizData[quizIndex]; const buttons=document.querySelectorAll('.quiz-option'); buttons.forEach(button=>button.disabled=true); buttons[item.a].classList.add('correct'); const feedback=document.getElementById('quizFeedback'); if(selected===item.a){quizScore++; feedback.textContent='🎉 Correto!'; feedback.style.color='#4ade80';} else {buttons[selected].classList.add('wrong'); feedback.textContent='❌ A correta está em verde.'; feedback.style.color='#f87171';} document.getElementById('quizNext').disabled=false;}
function nextQuiz(){quizIndex++; if(quizIndex>=quizData.length){finishQuiz(); return;} renderQuiz();}
function finishQuiz(){const percent=Math.round((quizScore/quizData.length)*100); document.getElementById('quizBar').style.width='100%'; document.getElementById('quizQuestion').textContent='🏁 Quiz concluído!'; document.getElementById('quizOptions').innerHTML=''; document.getElementById('quizScore').textContent=`Acertos: ${quizScore} de ${quizData.length} (${percent}%)`; const feedback=document.getElementById('quizFeedback'); feedback.textContent=percent>=80?'Excelente. A missão do dia ficou firme.':percent>=60?'Muito bom. Uma revisão curta amanhã consolida ainda mais.':'Bom começo. Vale revisar com calma e tentar novamente.'; feedback.style.color='#fde68a'; const next=document.getElementById('quizNext'); next.textContent='🔄 Tentar novamente'; next.disabled=false; next.onclick=()=>{quizIndex=0; quizScore=0; next.textContent='Próxima ➡️'; next.onclick=nextQuiz; renderQuiz();};}
document.getElementById('quizNext').onclick=nextQuiz; renderQuiz();}
async function fileExists(url){try{let res=await fetch(url,{method:'HEAD',cache:'no-store'}); if(res.ok) return true; if(res.status===405||res.status===0){res=await fetch(url,{method:'GET',cache:'no-store'}); return res.ok;} return false;}catch(e){return false;}}
async function initNavigation(data){const prevBtn=document.getElementById('btnPrev'); const nextBtn=document.getElementById('btnNext'); if(!window.AYKA || !Array.isArray(window.AYKA.dias)) return; const idx=window.AYKA.dias.findIndex(d=>d.numero===data.day); const prev=idx>0?window.AYKA.dias[idx-1]:null; const next=idx>=0 && idx<window.AYKA.dias.length-1 ? window.AYKA.dias[idx+1] : null; if(prevBtn){if(prev){prevBtn.href=`../${prev.file}`;}else{prevBtn.removeAttribute('href'); prevBtn.className='btn-secondary btn-disabled';}} if(nextBtn){if(next && await fileExists(`../${next.file}`)){nextBtn.href=`../${next.file}`; nextBtn.className='btn-primary';} else {nextBtn.removeAttribute('href'); nextBtn.className='btn-primary btn-disabled';}}}
function init(data){renderMeta(data); renderVideos(data); initQuiz(data); initNavigation(data); window.go=go; window.toggleAnswer=toggleAnswer;} return {init,go,toggleAnswer};})();