/*
  EIJI — configuração pedagógica v2
  Atualização focada apenas em cronograma, progressão, revisão, domínio e treino de prova.
  Design, identidade visual, layout e gamificação foram preservados.
*/

const projeto = {
  slug: "desafio-objetivo-eiji-rpg",
  titulo: "Jornada do Eiji — Sprint Objetivo",
  subtitulo: "14 semanas, 70 missões e sessões de 60 a 90 minutos por dia para chegar forte ao Desafio Objetivo.",
  aluno: "Eiji",
  totalDias: 70,
  totalSemanas: 14,
  missoesPorSemana: 5,
  dataInicio: "2026-03-23",
  dataFim: "2026-06-26",
  duracaoDiaria: "60 a 90 minutos",
  foco: "Português e Matemática",
  recompensas: {
    xpPorDia: 10,
    moedasPorDia: 3,
    xpPorBau: 25,
    moedasPorBau: 15
  },
  versaoCronograma: "v2_aprovacao",
  regraCentral: "manter design e gamificacao, otimizar apenas metodo, progressao, revisao e desempenho de prova"
};
const fases = [
  {
    id: "fase-1-base-5ano",
    icone: "📚",
    titulo: "Fase 1 — Base de Aprovação",
    reino: "Reino dos Fundamentos",
    inicioSemana: 1,
    fimSemana: 3,
    lore: "O foco aqui é fechar buracos cedo, criar leitura de comando e impedir que o aluno avance com base falsa.",
    objetivoAprovacao: "base diagnostica, consolidacao inicial e primeiro checkpoint forte"
  },
  {
    id: "fase-2-consolidacao-aceleracao",
    icone: "🧮",
    titulo: "Fase 2 — Consolidação com Aceleração",
    reino: "Reino da Agilidade",
    inicioSemana: 4,
    fimSemana: 6,
    lore: "Agora o Eiji ganha repertório com mais velocidade, mas sem perder precisão nem leitura de prova.",
    objetivoAprovacao: "automatizar habilidades úteis e aproximar o conteúdo do estilo do vestibulinho"
  },
  {
    id: "fase-3-ponte-6ano",
    icone: "🏹",
    titulo: "Fase 3 — Ponte de Complexidade",
    reino: "Reino da Estratégia",
    inicioSemana: 7,
    fimSemana: 9,
    lore: "As questões ficam mais densas. O treino passa a exigir cruzamento de pistas, alternativas próximas e mais controle atencional.",
    objetivoAprovacao: "sustentar atenção, aumentar densidade e treinar decisão"
  },
  {
    id: "fase-4-dominio-hibrido",
    icone: "⚔️",
    titulo: "Fase 4 — Domínio de Prova",
    reino: "Reino dos Simulados",
    inicioSemana: 10,
    fimSemana: 12,
    lore: "O estudo deixa de ser só conteúdo e vira comportamento de prova: tempo, decisão, correção e recuperação dos erros.",
    objetivoAprovacao: "medir, corrigir, reensinar e estabilizar desempenho"
  },
  {
    id: "fase-5-sprint-final",
    icone: "👑",
    titulo: "Fase 5 — Sprint Final",
    reino: "Reino da Coroa",
    inicioSemana: 13,
    fimSemana: 14,
    lore: "Na reta final, a revisão é cirúrgica: menos volume, mais precisão, mais confiança e menos erro bobo.",
    objetivoAprovacao: "lapidar pontos fracos e chegar inteiro para a prova"
  }
];
const semanas = [
  {
    semana: 1,
    fase: "fase-1-base-5ano",
    titulo: "Base e diagnóstico inicial",
    descricao: "Diagnóstico de leitura e matemática básica, com foco em ideia principal, fato x opinião e operações com significado.",
    narrativa: "O Eiji entra no mapa para descobrir onde já está forte e onde ainda perde ponto fácil. Nada de avançar no escuro.",
    reino: "Reino dos Fundamentos",
    tipoSemana: "diagnostico_base",
    objetivoAprovacao: "medir repertorio inicial, ensinar rotina de pensamento e abrir o caderno de erros",
    recompensaSemana: {
      icon: "📜",
      nome: "Bússola da Base",
      desc: "Mostra onde o herói já pisa firme e onde precisa reforço."
    }
  },
  {
    semana: 2,
    fase: "fase-1-base-5ano",
    titulo: "Automatização inicial",
    descricao: "Inferência, comando da questão, cálculo mental, multiplicação e divisão básicas para reduzir erro por impulso.",
    narrativa: "O herói para de responder no automático e aprende a ler pistas, comandos e operações com mais controle.",
    reino: "Reino dos Fundamentos",
    tipoSemana: "automatizacao_inicial",
    objetivoAprovacao: "reduzir erro de comando e iniciar bloco de prova leve",
    recompensaSemana: {
      icon: "🧠",
      nome: "Lupa do Comando",
      desc: "Ajuda a enxergar o que a questão realmente está pedindo."
    }
  },
  {
    semana: 3,
    fase: "fase-1-base-5ano",
    titulo: "Primeira consolidação forte",
    descricao: "Pontuação funcional, classes gramaticais úteis e frações básicas com o primeiro checkpoint mais exigente.",
    narrativa: "Aqui o Eiji mostra se a base realmente ficou de pé. O objetivo é impedir que uma lacuna pequena vire reprovação lá na frente.",
    reino: "Reino dos Fundamentos",
    tipoSemana: "checkpoint_forte",
    objetivoAprovacao: "consolidar a base antes de acelerar",
    recompensaSemana: {
      icon: "🛡️",
      nome: "Escudo da Consolidação",
      desc: "Protege contra avanço falso e excesso de confiança."
    }
  },
  {
    semana: 4,
    fase: "fase-2-consolidacao-aceleracao",
    titulo: "Leitura funcional e decimais",
    descricao: "Gêneros textuais, finalidade, leitura de enunciado, decimais e medidas com começo de treino cronometrado leve.",
    narrativa: "O mapa pede leitura mais útil: identificar propósito, dado relevante e unidade correta sem se perder nos detalhes.",
    reino: "Reino da Agilidade",
    tipoSemana: "leitura_funcional",
    objetivoAprovacao: "ligar leitura útil a matemática prática",
    recompensaSemana: {
      icon: "🌉",
      nome: "Ampulheta da Medida",
      desc: "Lembra que unidade errada derruba até conta certa."
    }
  },
  {
    semana: 5,
    fase: "fase-2-consolidacao-aceleracao",
    titulo: "Cotidiano de prova",
    descricao: "Coesão, pronomes em contexto, porcentagem, sistema monetário, gráficos e tirinhas em linguagem de prova real.",
    narrativa: "O herói começa a ler o mundo como prova: contexto, dado útil, pegadinha comum e decisão mais inteligente.",
    reino: "Reino da Agilidade",
    tipoSemana: "cotidiano_de_prova",
    objetivoAprovacao: "aproximar o treino do estilo mais frequente do vestibulinho",
    recompensaSemana: {
      icon: "💰",
      nome: "Bolsa do Contexto",
      desc: "Transforma contexto real em ponto de prova."
    }
  },
  {
    semana: 6,
    fase: "fase-2-consolidacao-aceleracao",
    titulo: "Forma, espaço e pegadinha",
    descricao: "Humor, ironia, reescrita, perímetro, área e geometria com primeiras alternativas mais próximas e leitura maliciosa.",
    narrativa: "Agora o Eiji aprende que prova boa não cobra só conteúdo: cobra atenção fina, comparação e leitura menos ingênua.",
    reino: "Reino da Agilidade",
    tipoSemana: "alternativas_proximas",
    objetivoAprovacao: "começar a treinar pegadinhas reais",
    recompensaSemana: {
      icon: "📐",
      nome: "Compasso da Precisão",
      desc: "Ajuda a enxergar detalhe, forma e alternativa enganosa."
    }
  },
  {
    semana: 7,
    fase: "fase-3-ponte-6ano",
    titulo: "Cruzamento de informações",
    descricao: "Comparação entre textos, opinião x fato, operações combinadas e problemas mais longos com mini prova curta.",
    narrativa: "O herói deixa de resolver blocos simples e passa a sustentar atenção em enunciados mais densos.",
    reino: "Reino da Estratégia",
    tipoSemana: "ponte_de_complexidade",
    objetivoAprovacao: "ganhar resistência cognitiva sem perder clareza",
    recompensaSemana: {
      icon: "🏹",
      nome: "Arco da Sustentação",
      desc: "Favorece foco em textos e problemas com mais etapas."
    }
  },
  {
    semana: 8,
    fase: "fase-3-ponte-6ano",
    titulo: "Coerência e alternativas",
    descricao: "Reescrita, coerência, razão simples, média e tabelas densas com treino de eliminação de alternativas.",
    narrativa: "Cada alternativa passa a ter armadilha. O herói precisa ler melhor, comparar melhor e escolher com mais critério.",
    reino: "Reino da Estratégia",
    tipoSemana: "eliminacao_de_alternativas",
    objetivoAprovacao: "aprender a decidir melhor entre opções parecidas",
    recompensaSemana: {
      icon: "🗝️",
      nome: "Chave da Escolha",
      desc: "Abre o caminho para acertar sem depender de chute."
    }
  },
  {
    semana: 9,
    fase: "fase-3-ponte-6ano",
    titulo: "Pegadinhas reais",
    descricao: "Efeito de sentido, verbal e não verbal, medidas, conversões e geometria aplicada com dois blocos sob tempo.",
    narrativa: "O mapa fica menos literal. O herói precisa controlar distração, detalhes e ritmo ao mesmo tempo.",
    reino: "Reino da Estratégia",
    tipoSemana: "pressao_controlada",
    objetivoAprovacao: "diminuir erro por desatenção e consolidar matemática aplicada",
    recompensaSemana: {
      icon: "👁️",
      nome: "Olho da Atenção",
      desc: "Reduz tropeços por leitura superficial e marcação apressada."
    }
  },
  {
    semana: 10,
    fase: "fase-4-dominio-hibrido",
    titulo: "Mini simulado 1",
    descricao: "Primeiro ciclo formal de simulado, correção guiada e reensino dos erros mais críticos.",
    narrativa: "O Eiji entra na arena para medir de verdade o que sustenta sob pressão e o que desmorona quando o relógio pesa.",
    reino: "Reino dos Simulados",
    tipoSemana: "simulado_medicao",
    objetivoAprovacao: "medir desempenho real e abrir recuperação cirúrgica",
    recompensaSemana: {
      icon: "🏟️",
      nome: "Troféu do Diagnóstico",
      desc: "Recompensa quem transforma erro em informação útil."
    }
  },
  {
    semana: 11,
    fase: "fase-4-dominio-hibrido",
    titulo: "Mini simulado 2",
    descricao: "Novo ciclo de simulado com foco em consistência, leitura de comando, recuperação de erros e estabilidade.",
    narrativa: "A diferença agora não é só saber mais. É oscilar menos, corrigir rápido e sustentar resultado.",
    reino: "Reino dos Simulados",
    tipoSemana: "estabilizacao",
    objetivoAprovacao: "reduzir oscilacao e consolidar comportamento de prova",
    recompensaSemana: {
      icon: "🥇",
      nome: "Lanterna da Correção",
      desc: "Ilumina os erros que mais insistem em voltar."
    }
  },
  {
    semana: 12,
    fase: "fase-4-dominio-hibrido",
    titulo: "Tempo e estratégia",
    descricao: "Treino sob pressão com gestão de tempo, marcação inteligente, revisão final de protocolo e foco sob relógio.",
    narrativa: "O herói aprende que prova não premia só quem sabe. Premia quem sabe decidir dentro do tempo.",
    reino: "Reino dos Simulados",
    tipoSemana: "tempo_e_estrategia",
    objetivoAprovacao: "criar protocolo mental para não travar na prova",
    recompensaSemana: {
      icon: "⏳",
      nome: "Relógio de Batalha",
      desc: "Fortalece ritmo, ordem de ataque e revisão inteligente."
    }
  },
  {
    semana: 13,
    fase: "fase-5-sprint-final",
    titulo: "Revisão baseada em erro",
    descricao: "Português e Matemática mais cobrados, puxados principalmente pelo histórico de erros e pontos fracos reais.",
    narrativa: "Agora o Eiji não revisa tudo igual. Ele revisa o que mais ameaça sua aprovação.",
    reino: "Reino da Coroa",
    tipoSemana: "revisao_cirurgica",
    objetivoAprovacao: "trocar revisão genérica por revisão de alto impacto",
    recompensaSemana: {
      icon: "🧭",
      nome: "Mapa do Essencial",
      desc: "Mostra o que realmente merece energia na reta final."
    }
  },
  {
    semana: 14,
    fase: "fase-5-sprint-final",
    titulo: "Lapidação final",
    descricao: "Sprint final com simulado curto, correção leve, confiança baseada em evidência e véspera inteligente.",
    narrativa: "O herói não precisa de excesso. Precisa de calma, confiança e cabeça limpa para converter tudo que treinou.",
    reino: "Reino da Coroa",
    tipoSemana: "lapidacao_final",
    objetivoAprovacao: "chegar inteiro, atento e confiante para o dia decisivo",
    recompensaSemana: {
      icon: "👑",
      nome: "Coroa da Confiança",
      desc: "Símbolo de preparo sem sobrecarga e sem pânico."
    }
  }
];
const dias = [
  {
    numero: 1,
    data: "2026-03-23",
    semana: 1,
    fase: "fase-1-base-5ano",
    titulo: "Ideia Principal do Texto",
    disciplina: "Português",
    disciplinaNome: "Português",
    disciplinaIcone: "📘",
    reino: "Reino dos Fundamentos",
    reinoIcone: "📚",
    expansao: "Leitura literal, ideia central e comando principal de prova.",
    raridade: "comum",
    xp: 10,
    moedas: 3,
    arquivo: "apostilas/dia-001.html",
    iconeMissao: "📘",
    funcaoPedagogica: "diagnostico_inicial",
    habilidadePrincipal: "identificar a ideia principal sem confundir com detalhe",
    habilidadeSecundaria: "registrar primeiros erros de leitura e foco",
    focoDeProva: "nao responder pela frase mais bonita",
    tempoMeta: "60 a 75 min",
    criterioDominio: "80% no quiz + acerto da questao-ancora de ideia principal",
    blocoCronometrado: null,
    revisao24hDe: null,
    revisaoSemanal: false,
    revisaoCumulativa: "sem revisão cumulativa no Dia 1; o conteúdo volta no início do Dia 2",
    cadernoDeErrosObrigatorio: true,
    prioridadeAprovacao: "média"
  },
  {
    numero: 2,
    data: "2026-03-24",
    semana: 1,
    fase: "fase-1-base-5ano",
    titulo: "Fatos, Opiniões e Adição/Subtração",
    disciplina: "Português + Matemática",
    disciplinaNome: "Português + Matemática",
    disciplinaIcone: "⚔️",
    reino: "Reino dos Fundamentos",
    reinoIcone: "📚",
    expansao: "Distinguir dado comprovável de julgamento e escolher entre somar e subtrair.",
    raridade: "comum",
    xp: 10,
    moedas: 3,
    arquivo: "apostilas/dia-002.html",
    iconeMissao: "⚖️",
    funcaoPedagogica: "conteudo_novo_com_revisao_24h",
    habilidadePrincipal: "separar fato de opinião e operação de aumento ou diminuição",
    habilidadeSecundaria: "recuperar ideia principal do Dia 1",
    focoDeProva: "nao confundir gosto com dado e nao operar no impulso",
    tempoMeta: "70 a 80 min",
    criterioDominio: "80% no quiz + justificar 1 fato, 1 opinião e 1 operação correta",
    blocoCronometrado: null,
    revisao24hDe: 1,
    revisaoSemanal: false,
    revisaoCumulativa: "retoma oralmente a habilidade do Dia 1",
    cadernoDeErrosObrigatorio: true,
    prioridadeAprovacao: "média"
  },
  {
    numero: 3,
    data: "2026-03-25",
    semana: 1,
    fase: "fase-1-base-5ano",
    titulo: "Informação Explícita e Implícita",
    disciplina: "Português + aquecimento matemático",
    disciplinaNome: "Português + aquecimento matemático",
    disciplinaIcone: "🔎",
    reino: "Reino dos Fundamentos",
    reinoIcone: "📚",
    expansao: "Treino de pistas visíveis e inferências iniciais no texto, com cálculo mental leve.",
    raridade: "comum",
    xp: 10,
    moedas: 3,
    arquivo: "apostilas/dia-003.html",
    iconeMissao: "🔎",
    funcaoPedagogica: "conteudo_novo_com_revisao_24h",
    habilidadePrincipal: "localizar o explícito e inferir o implícito por pistas",
    habilidadeSecundaria: "cálculo mental por compensação simples",
    focoDeProva: "nao inventar resposta sem pista textual",
    tempoMeta: "70 a 80 min",
    criterioDominio: "80% no quiz + acertar ao menos 2 inferencias justificadas",
    blocoCronometrado: null,
    revisao24hDe: 2,
    revisaoSemanal: false,
    revisaoCumulativa: "retoma fato x opinião e operação básica",
    cadernoDeErrosObrigatorio: true,
    prioridadeAprovacao: "média"
  },
  {
    numero: 4,
    data: "2026-03-26",
    semana: 1,
    fase: "fase-1-base-5ano",
    titulo: "Adição, Subtração e Problemas do Cotidiano",
    disciplina: "Matemática",
    disciplinaNome: "Matemática",
    disciplinaIcone: "🧮",
    reino: "Reino dos Fundamentos",
    reinoIcone: "📚",
    expansao: "Contas com significado, enunciado e resolução passo a passo.",
    raridade: "comum",
    xp: 10,
    moedas: 3,
    arquivo: "apostilas/dia-004.html",
    iconeMissao: "➕",
    funcaoPedagogica: "consolidacao_de_base",
    habilidadePrincipal: "selecionar a operação correta a partir do enunciado",
    habilidadeSecundaria: "revisar explícito e implícito antes da decisão matemática",
    focoDeProva: "entender a pergunta antes da conta",
    tempoMeta: "75 a 90 min",
    criterioDominio: "80% no quiz + resolver 3 problemas justificando a operação",
    blocoCronometrado: {
      ativo: true,
      duracaoMin: 6,
      objetivo: "primeiro bloco leve de decisão sob tempo"
    },
    revisao24hDe: 3,
    revisaoSemanal: false,
    revisaoCumulativa: "retoma operações do Dia 2",
    cadernoDeErrosObrigatorio: true,
    prioridadeAprovacao: "média"
  },
  {
    numero: 5,
    data: "2026-03-27",
    semana: 1,
    fase: "fase-1-base-5ano",
    titulo: "Revisão da Semana 1 + Desafio Misto 1",
    disciplina: "Português + Matemática",
    disciplinaNome: "Português + Matemática",
    disciplinaIcone: "⚔️",
    reino: "Reino dos Fundamentos",
    reinoIcone: "📚",
    expansao: "Checkpoint de base com revisão da semana, mini bloco misto e abertura formal do caderno de erros.",
    raridade: "incomum",
    xp: 12,
    moedas: 4,
    arquivo: "apostilas/dia-005.html",
    iconeMissao: "🎯",
    funcaoPedagogica: "checkpoint_semanal",
    habilidadePrincipal: "misturar leitura e matemática sem perder clareza",
    habilidadeSecundaria: "classificar erros em leitura, atenção ou cálculo",
    focoDeProva: "acertar com calma, não só terminar",
    tempoMeta: "75 a 90 min",
    criterioDominio: "75% no bloco misto + caderno de erros preenchido",
    blocoCronometrado: {
      ativo: true,
      duracaoMin: 10,
      objetivo: "mini checkpoint de base"
    },
    revisao24hDe: 4,
    revisaoSemanal: true,
    revisaoCumulativa: "sintetiza Dias 1 a 4",
    cadernoDeErrosObrigatorio: true,
    prioridadeAprovacao: "média"
  },
  {
    numero: 6,
    data: "2026-03-30",
    semana: 2,
    fase: "fase-1-base-5ano",
    titulo: "Inferência Inicial + Cálculo Mental",
    disciplina: "Português + Matemática",
    disciplinaNome: "Português + Matemática",
    disciplinaIcone: "⚔️",
    reino: "Reino dos Fundamentos",
    reinoIcone: "📚",
    expansao: "Revisão 24h da Semana 1 e inferência com cálculo mental estratégico.",
    raridade: "comum",
    xp: 10,
    moedas: 3,
    arquivo: "apostilas/dia-006.html",
    iconeMissao: "⚔️",
    funcaoPedagogica: "novo_ciclo_com_revisao",
    habilidadePrincipal: "inferir por reação, contexto e pista verbal",
    habilidadeSecundaria: "usar cálculo mental por arredondamento",
    focoDeProva: "inferência sem pista vira chute",
    tempoMeta: "75 a 90 min",
    criterioDominio: "80% no quiz + 2 inferencias justificadas + 2 contas por estratégia",
    blocoCronometrado: null,
    revisao24hDe: 5,
    revisaoSemanal: false,
    revisaoCumulativa: "revisita ideia principal e operação com significado",
    cadernoDeErrosObrigatorio: true,
    prioridadeAprovacao: "média"
  },
  {
    numero: 7,
    data: "2026-03-31",
    semana: 2,
    fase: "fase-1-base-5ano",
    titulo: "Sinônimos, Antônimos e Tabuada Estratégica",
    disciplina: "Português + Matemática",
    disciplinaNome: "Português + Matemática",
    disciplinaIcone: "⚔️",
    reino: "Reino dos Fundamentos",
    reinoIcone: "📚",
    expansao: "Vocabulário no contexto e multiplicação por padrões, não por decoreba cega.",
    raridade: "comum",
    xp: 10,
    moedas: 3,
    arquivo: "apostilas/dia-007.html",
    iconeMissao: "⚔️",
    funcaoPedagogica: "automatizacao_controlada",
    habilidadePrincipal: "reconhecer relação de sentido entre palavras no contexto",
    habilidadeSecundaria: "multiplicar por grupos iguais e padrões simples",
    focoDeProva: "nao marcar sinonimo fora do contexto",
    tempoMeta: "70 a 85 min",
    criterioDominio: "80% no quiz + 1 justificativa de sinonimo contextual + 1 de multiplicação",
    blocoCronometrado: null,
    revisao24hDe: 6,
    revisaoSemanal: false,
    revisaoCumulativa: "retoma inferência e cálculo mental",
    cadernoDeErrosObrigatorio: true,
    prioridadeAprovacao: "média"
  },
  {
    numero: 8,
    data: "2026-04-01",
    semana: 2,
    fase: "fase-1-base-5ano",
    titulo: "Comando da Questão + Multiplicação",
    disciplina: "Português + Matemática",
    disciplinaNome: "Português + Matemática",
    disciplinaIcone: "⚔️",
    reino: "Reino dos Fundamentos",
    reinoIcone: "📚",
    expansao: "Ler o que a questão realmente pede e ligar isso à multiplicação aplicada.",
    raridade: "comum",
    xp: 10,
    moedas: 3,
    arquivo: "apostilas/dia-008.html",
    iconeMissao: "⚔️",
    funcaoPedagogica: "leitura_de_comando",
    habilidadePrincipal: "identificar o verbo de comando e agir conforme ele",
    habilidadeSecundaria: "usar multiplicação em situações de grupos iguais",
    focoDeProva: "responder ao que foi pedido, não ao que parece familiar",
    tempoMeta: "70 a 85 min",
    criterioDominio: "80% no quiz + acerto da questão-âncora de comando",
    blocoCronometrado: {
      ativo: true,
      duracaoMin: 5,
      objetivo: "ler comando e responder sem releitura longa"
    },
    revisao24hDe: 7,
    revisaoSemanal: false,
    revisaoCumulativa: "retoma vocabulário e multiplicação",
    cadernoDeErrosObrigatorio: true,
    prioridadeAprovacao: "média"
  },
  {
    numero: 9,
    data: "2026-04-02",
    semana: 2,
    fase: "fase-1-base-5ano",
    titulo: "Sequência Lógica + Divisão",
    disciplina: "Português + Matemática",
    disciplinaNome: "Português + Matemática",
    disciplinaIcone: "⚔️",
    reino: "Reino dos Fundamentos",
    reinoIcone: "📚",
    expansao: "Ordem do raciocínio e divisão como repartição com conferência pela multiplicação.",
    raridade: "comum",
    xp: 10,
    moedas: 3,
    arquivo: "apostilas/dia-009.html",
    iconeMissao: "⚔️",
    funcaoPedagogica: "organizacao_de_raciocinio",
    habilidadePrincipal: "organizar fatos em ordem lógica e dividir com sentido",
    habilidadeSecundaria: "conferir divisão pela multiplicação",
    focoDeProva: "nao inverter etapas nem repartir sem entender o total",
    tempoMeta: "70 a 85 min",
    criterioDominio: "80% no quiz + 2 divisões conferidas pela multiplicação",
    blocoCronometrado: null,
    revisao24hDe: 8,
    revisaoSemanal: false,
    revisaoCumulativa: "retoma leitura de comando",
    cadernoDeErrosObrigatorio: true,
    prioridadeAprovacao: "média"
  },
  {
    numero: 10,
    data: "2026-04-03",
    semana: 2,
    fase: "fase-1-base-5ano",
    titulo: "Revisão da Semana 2 + Desafio Misto 2",
    disciplina: "Português + Matemática",
    disciplinaNome: "Português + Matemática",
    disciplinaIcone: "⚔️",
    reino: "Reino dos Fundamentos",
    reinoIcone: "📚",
    expansao: "Revisão 24h do Dia 9, checkpoint semanal e primeiro bloco cronometrado mais explícito.",
    raridade: "incomum",
    xp: 12,
    moedas: 4,
    arquivo: "apostilas/dia-010.html",
    iconeMissao: "🎯",
    funcaoPedagogica: "checkpoint_semanal_com_tempo",
    habilidadePrincipal: "misturar inferência, comando e operações básicas com ritmo controlado",
    habilidadeSecundaria: "separar erro de conteúdo de erro de prova",
    focoDeProva: "não acelerar demais quando o relógio aparece",
    tempoMeta: "75 a 90 min",
    criterioDominio: "75% no bloco misto + erro classificado por categoria",
    blocoCronometrado: {
      ativo: true,
      duracaoMin: 12,
      objetivo: "primeiro checkpoint com sensação real de tempo"
    },
    revisao24hDe: 9,
    revisaoSemanal: true,
    revisaoCumulativa: "sintetiza Dias 6 a 9",
    cadernoDeErrosObrigatorio: true,
    prioridadeAprovacao: "média"
  },
  {
    numero: 11,
    data: "2026-04-06",
    semana: 3,
    fase: "fase-1-base-5ano",
    titulo: "Pontuação que Muda Sentido + Frações Básicas",
    disciplina: "Português + Matemática",
    disciplinaNome: "Português + Matemática",
    disciplinaIcone: "⚔️",
    reino: "Reino dos Fundamentos",
    reinoIcone: "📚",
    expansao: "Pontuação em contexto e leitura inicial de frações.",
    raridade: "comum",
    xp: 10,
    moedas: 3,
    arquivo: "apostilas/dia-011.html",
    iconeMissao: "⚔️",
    funcaoPedagogica: "novo_conteudo",
    habilidadePrincipal: "perceber como a pontuação altera o sentido",
    habilidadeSecundaria: "reconhecer parte-todo em frações simples",
    focoDeProva: "não ignorar vírgula, ponto e comparação visual",
    tempoMeta: "70 a 85 min",
    criterioDominio: "80% no quiz + 1 reescrita com mudança de pontuação + 2 frações lidas corretamente",
    blocoCronometrado: null,
    revisao24hDe: 10,
    revisaoSemanal: false,
    revisaoCumulativa: "retoma comando e divisão",
    cadernoDeErrosObrigatorio: true,
    prioridadeAprovacao: "alta"
  },
  {
    numero: 12,
    data: "2026-04-07",
    semana: 3,
    fase: "fase-1-base-5ano",
    titulo: "Classes de Palavras + Frações na Prática",
    disciplina: "Português + Matemática",
    disciplinaNome: "Português + Matemática",
    disciplinaIcone: "⚔️",
    reino: "Reino dos Fundamentos",
    reinoIcone: "📚",
    expansao: "Substantivo, verbo, adjetivo e frações no cotidiano.",
    raridade: "comum",
    xp: 10,
    moedas: 3,
    arquivo: "apostilas/dia-012.html",
    iconeMissao: "⚔️",
    funcaoPedagogica: "novo_conteudo",
    habilidadePrincipal: "reconhecer classes úteis em função do sentido",
    habilidadeSecundaria: "aplicar frações em exemplos concretos",
    focoDeProva: "não decorar classe sem olhar a função na frase",
    tempoMeta: "70 a 85 min",
    criterioDominio: "80% no quiz + identificar classe em contexto + representar 2 frações do cotidiano",
    blocoCronometrado: null,
    revisao24hDe: 11,
    revisaoSemanal: false,
    revisaoCumulativa: "retoma pontuação e fração básica",
    cadernoDeErrosObrigatorio: true,
    prioridadeAprovacao: "alta"
  },
  {
    numero: 13,
    data: "2026-04-08",
    semana: 3,
    fase: "fase-1-base-5ano",
    titulo: "Referência Pronominal + Frações Equivalentes",
    disciplina: "Português + Matemática",
    disciplinaNome: "Português + Matemática",
    disciplinaIcone: "⚔️",
    reino: "Reino dos Fundamentos",
    reinoIcone: "📚",
    expansao: "Quem é quem no texto e equivalência de frações.",
    raridade: "comum",
    xp: 10,
    moedas: 3,
    arquivo: "apostilas/dia-013.html",
    iconeMissao: "⚔️",
    funcaoPedagogica: "conexao_de_pistas",
    habilidadePrincipal: "rastrear referente pronominal sem se perder",
    habilidadeSecundaria: "comparar frações equivalentes por desenho e raciocínio",
    focoDeProva: "não trocar o referente por proximidade visual",
    tempoMeta: "70 a 85 min",
    criterioDominio: "80% no quiz + acertar referente em 3 frases + 2 equivalências",
    blocoCronometrado: null,
    revisao24hDe: 12,
    revisaoSemanal: false,
    revisaoCumulativa: "retoma classes e frações",
    cadernoDeErrosObrigatorio: true,
    prioridadeAprovacao: "alta"
  },
  {
    numero: 14,
    data: "2026-04-09",
    semana: 3,
    fase: "fase-1-base-5ano",
    titulo: "Ortografia Frequente + Comparação de Frações",
    disciplina: "Português + Matemática",
    disciplinaNome: "Português + Matemática",
    disciplinaIcone: "⚔️",
    reino: "Reino dos Fundamentos",
    reinoIcone: "📚",
    expansao: "Erros comuns de escrita e comparação entre frações.",
    raridade: "comum",
    xp: 10,
    moedas: 3,
    arquivo: "apostilas/dia-014.html",
    iconeMissao: "⚔️",
    funcaoPedagogica: "consolidacao_de_base",
    habilidadePrincipal: "evitar erros frequentes de ortografia funcional",
    habilidadeSecundaria: "comparar frações por referência visual e numerador/denominador",
    focoDeProva: "não cair em erro bobo por distração gráfica",
    tempoMeta: "70 a 85 min",
    criterioDominio: "80% no quiz + 1 mini lista ortográfica + 3 comparações corretas",
    blocoCronometrado: {
      ativo: true,
      duracaoMin: 6,
      objetivo: "escolher rápido entre frações simples"
    },
    revisao24hDe: 13,
    revisaoSemanal: false,
    revisaoCumulativa: "retoma referente e equivalência",
    cadernoDeErrosObrigatorio: true,
    prioridadeAprovacao: "alta"
  },
  {
    numero: 15,
    data: "2026-04-10",
    semana: 3,
    fase: "fase-1-base-5ano",
    titulo: "Revisão da Semana 3 + Checkpoint da Base",
    disciplina: "Português + Matemática",
    disciplinaNome: "Português + Matemática",
    disciplinaIcone: "⚔️",
    reino: "Reino dos Fundamentos",
    reinoIcone: "📚",
    expansao: "Primeiro checkpoint forte do projeto, misturando base inteira, correção e decisão de avanço.",
    raridade: "raro",
    xp: 15,
    moedas: 5,
    arquivo: "apostilas/dia-015.html",
    iconeMissao: "🎯",
    funcaoPedagogica: "checkpoint_forte",
    habilidadePrincipal: "provar que a base suporta mistura de conteúdos",
    habilidadeSecundaria: "decidir o que volta na semana 4 pelo caderno de erros",
    focoDeProva: "não avançar com buraco escondido",
    tempoMeta: "80 a 90 min",
    criterioDominio: "70% no checkpoint + caderno de erros atualizado + plano de reforço",
    blocoCronometrado: {
      ativo: true,
      duracaoMin: 15,
      objetivo: "primeiro checkpoint mais exigente"
    },
    revisao24hDe: 14,
    revisaoSemanal: true,
    revisaoCumulativa: "sintetiza Semanas 1 a 3",
    cadernoDeErrosObrigatorio: true,
    prioridadeAprovacao: "alta"
  },
  {
    numero: 16,
    data: "2026-04-13",
    semana: 4,
    fase: "fase-2-consolidacao-aceleracao",
    titulo: "Gêneros Textuais + Números Decimais",
    disciplina: "Português + Matemática",
    disciplinaNome: "Português + Matemática",
    disciplinaIcone: "⚔️",
    reino: "Reino da Agilidade",
    reinoIcone: "🧮",
    expansao: "Reconhecer gênero e finalidade, com introdução aos decimais.",
    raridade: "comum",
    xp: 10,
    moedas: 3,
    arquivo: "apostilas/dia-016.html",
    iconeMissao: "⚔️",
    funcaoPedagogica: "leitura_funcional",
    habilidadePrincipal: "identificar gênero para antecipar finalidade e linguagem",
    habilidadeSecundaria: "compreender valor posicional em decimais",
    focoDeProva: "usar o tipo de texto como pista de resposta",
    tempoMeta: "70 a 85 min",
    criterioDominio: "80% no quiz + gênero justificado + leitura correta de decimais",
    blocoCronometrado: null,
    revisao24hDe: 15,
    revisaoSemanal: false,
    revisaoCumulativa: "retoma pontos fracos do checkpoint",
    cadernoDeErrosObrigatorio: true,
    prioridadeAprovacao: "alta"
  },
  {
    numero: 17,
    data: "2026-04-14",
    semana: 4,
    fase: "fase-2-consolidacao-aceleracao",
    titulo: "Finalidade do Texto + Adição com Decimais",
    disciplina: "Português + Matemática",
    disciplinaNome: "Português + Matemática",
    disciplinaIcone: "⚔️",
    reino: "Reino da Agilidade",
    reinoIcone: "🧮",
    expansao: "Propósito do texto e soma de valores decimais.",
    raridade: "comum",
    xp: 10,
    moedas: 3,
    arquivo: "apostilas/dia-017.html",
    iconeMissao: "⚔️",
    funcaoPedagogica: "leitura_funcional",
    habilidadePrincipal: "distinguir informar, convencer, orientar ou divertir",
    habilidadeSecundaria: "somar decimais alinhando vírgula com sentido",
    focoDeProva: "não errar propósito por palavra isolada",
    tempoMeta: "70 a 85 min",
    criterioDominio: "80% no quiz + 2 finalidades justificadas + 2 somas decimais corretas",
    blocoCronometrado: null,
    revisao24hDe: 16,
    revisaoSemanal: false,
    revisaoCumulativa: "retoma gênero e decimal",
    cadernoDeErrosObrigatorio: true,
    prioridadeAprovacao: "alta"
  },
  {
    numero: 18,
    data: "2026-04-15",
    semana: 4,
    fase: "fase-2-consolidacao-aceleracao",
    titulo: "Leitura de Enunciado + Subtração com Decimais",
    disciplina: "Português + Matemática",
    disciplinaNome: "Português + Matemática",
    disciplinaIcone: "⚔️",
    reino: "Reino da Agilidade",
    reinoIcone: "🧮",
    expansao: "Separar dado útil de distração e subtrair valores decimais.",
    raridade: "comum",
    xp: 10,
    moedas: 3,
    arquivo: "apostilas/dia-018.html",
    iconeMissao: "⚔️",
    funcaoPedagogica: "filtro_de_dados",
    habilidadePrincipal: "filtrar informação relevante no enunciado",
    habilidadeSecundaria: "subtrair decimais em problemas simples",
    focoDeProva: "não levar dado extra para a conta",
    tempoMeta: "70 a 85 min",
    criterioDominio: "80% no quiz + acerto da questão-âncora de dado útil",
    blocoCronometrado: {
      ativo: true,
      duracaoMin: 5,
      objetivo: "filtrar dado útil sob leve pressão"
    },
    revisao24hDe: 17,
    revisaoSemanal: false,
    revisaoCumulativa: "retoma finalidade textual",
    cadernoDeErrosObrigatorio: true,
    prioridadeAprovacao: "alta"
  },
  {
    numero: 19,
    data: "2026-04-16",
    semana: 4,
    fase: "fase-2-consolidacao-aceleracao",
    titulo: "Resolução Guiada + Medidas de Comprimento",
    disciplina: "Português + Matemática",
    disciplinaNome: "Português + Matemática",
    disciplinaIcone: "⚔️",
    reino: "Reino da Agilidade",
    reinoIcone: "🧮",
    expansao: "Texto curto, unidades, conversão e comparação.",
    raridade: "comum",
    xp: 10,
    moedas: 3,
    arquivo: "apostilas/dia-019.html",
    iconeMissao: "⚔️",
    funcaoPedagogica: "conteudo_aplicado",
    habilidadePrincipal: "resolver com roteiro e conferir unidade",
    habilidadeSecundaria: "comparar e converter medidas simples",
    focoDeProva: "unidade errada destrói questão certa",
    tempoMeta: "70 a 85 min",
    criterioDominio: "80% no quiz + 2 conversões corretas + 1 problema explicado",
    blocoCronometrado: null,
    revisao24hDe: 18,
    revisaoSemanal: false,
    revisaoCumulativa: "retoma leitura de enunciado",
    cadernoDeErrosObrigatorio: true,
    prioridadeAprovacao: "alta"
  },
  {
    numero: 20,
    data: "2026-04-17",
    semana: 4,
    fase: "fase-2-consolidacao-aceleracao",
    titulo: "Revisão da Semana 4 + Desafio Misto 4",
    disciplina: "Português + Matemática",
    disciplinaNome: "Português + Matemática",
    disciplinaIcone: "⚔️",
    reino: "Reino da Agilidade",
    reinoIcone: "🧮",
    expansao: "Revisão da semana com primeiro bloco funcional de prova curta.",
    raridade: "incomum",
    xp: 12,
    moedas: 4,
    arquivo: "apostilas/dia-020.html",
    iconeMissao: "🎯",
    funcaoPedagogica: "checkpoint_funcional",
    habilidadePrincipal: "misturar leitura útil, decimal e medida em ritmo estável",
    habilidadeSecundaria: "registrar erro de unidade, de comando e de distração",
    focoDeProva: "manter clareza sob bloco cronometrado",
    tempoMeta: "75 a 90 min",
    criterioDominio: "75% no bloco misto + erro classificado com ação de correção",
    blocoCronometrado: {
      ativo: true,
      duracaoMin: 12,
      objetivo: "mini prova funcional"
    },
    revisao24hDe: 19,
    revisaoSemanal: true,
    revisaoCumulativa: "sintetiza Semana 4 + recupera ponto fraco da base",
    cadernoDeErrosObrigatorio: true,
    prioridadeAprovacao: "alta"
  },
  {
    numero: 21,
    data: "2026-04-20",
    semana: 5,
    fase: "fase-2-consolidacao-aceleracao",
    titulo: "Coesão Textual + Sistema Monetário",
    disciplina: "Português + Matemática",
    disciplinaNome: "Português + Matemática",
    disciplinaIcone: "⚔️",
    reino: "Reino da Agilidade",
    reinoIcone: "🧮",
    expansao: "Conectivos e sentido global, com dinheiro, troco e comparação.",
    raridade: "comum",
    xp: 10,
    moedas: 3,
    arquivo: "apostilas/dia-021.html",
    iconeMissao: "⚔️",
    funcaoPedagogica: "cotidiano_de_prova",
    habilidadePrincipal: "entender conectivos como pistas de relação entre ideias",
    habilidadeSecundaria: "resolver troco e comparação monetária",
    focoDeProva: "não ignorar conectivo pequeno que muda tudo",
    tempoMeta: "70 a 85 min",
    criterioDominio: "80% no quiz + 2 conectivos explicados + 2 situações de troco",
    blocoCronometrado: null,
    revisao24hDe: 20,
    revisaoSemanal: false,
    revisaoCumulativa: "retoma medida e dado útil",
    cadernoDeErrosObrigatorio: true,
    prioridadeAprovacao: "alta"
  },
  {
    numero: 22,
    data: "2026-04-21",
    semana: 5,
    fase: "fase-2-consolidacao-aceleracao",
    titulo: "Pronomes em Contexto + Porcentagem Básica",
    disciplina: "Português + Matemática",
    disciplinaNome: "Português + Matemática",
    disciplinaIcone: "⚔️",
    reino: "Reino da Agilidade",
    reinoIcone: "🧮",
    expansao: "Retomada textual e porcentagem em linguagem simples.",
    raridade: "comum",
    xp: 10,
    moedas: 3,
    arquivo: "apostilas/dia-022.html",
    iconeMissao: "⚔️",
    funcaoPedagogica: "cotidiano_de_prova",
    habilidadePrincipal: "ligar pronome ao termo correto no contexto",
    habilidadeSecundaria: "calcular porcentagem básica em situações diretas",
    focoDeProva: "não trocar referente nem percentual por aproximação apressada",
    tempoMeta: "70 a 85 min",
    criterioDominio: "80% no quiz + 2 referentes corretos + 2 percentuais básicos",
    blocoCronometrado: null,
    revisao24hDe: 21,
    revisaoSemanal: false,
    revisaoCumulativa: "retoma coesão e sistema monetário",
    cadernoDeErrosObrigatorio: true,
    prioridadeAprovacao: "alta"
  },
  {
    numero: 23,
    data: "2026-04-22",
    semana: 5,
    fase: "fase-2-consolidacao-aceleracao",
    titulo: "Ortografia Atenta + Descontos e Acréscimos",
    disciplina: "Português + Matemática",
    disciplinaNome: "Português + Matemática",
    disciplinaIcone: "⚔️",
    reino: "Reino da Agilidade",
    reinoIcone: "🧮",
    expansao: "Revisão de escrita e noções práticas de desconto e acréscimo.",
    raridade: "comum",
    xp: 10,
    moedas: 3,
    arquivo: "apostilas/dia-023.html",
    iconeMissao: "⚔️",
    funcaoPedagogica: "cotidiano_de_prova",
    habilidadePrincipal: "evitar erro ortográfico frequente em leitura e escrita curta",
    habilidadeSecundaria: "entender desconto e aumento em linguagem comercial",
    focoDeProva: "não confundir desconto com valor final",
    tempoMeta: "70 a 85 min",
    criterioDominio: "80% no quiz + 1 acerto em desconto + 1 em acréscimo",
    blocoCronometrado: {
      ativo: true,
      duracaoMin: 6,
      objetivo: "decidir rápido entre aumento e desconto"
    },
    revisao24hDe: 22,
    revisaoSemanal: false,
    revisaoCumulativa: "retoma porcentagem básica",
    cadernoDeErrosObrigatorio: true,
    prioridadeAprovacao: "alta"
  },
  {
    numero: 24,
    data: "2026-04-23",
    semana: 5,
    fase: "fase-2-consolidacao-aceleracao",
    titulo: "Interpretação de Tiras + Gráficos e Tabelas",
    disciplina: "Português + Matemática",
    disciplinaNome: "Português + Matemática",
    disciplinaIcone: "⚔️",
    reino: "Reino da Agilidade",
    reinoIcone: "🧮",
    expansao: "Humor visual e leitura de dados com contexto.",
    raridade: "comum",
    xp: 10,
    moedas: 3,
    arquivo: "apostilas/dia-024.html",
    iconeMissao: "⚔️",
    funcaoPedagogica: "cotidiano_de_prova",
    habilidadePrincipal: "ler humor, intenção e informação em texto verbal e não verbal",
    habilidadeSecundaria: "extrair dado central de gráfico e tabela",
    focoDeProva: "não olhar só desenho ou só número",
    tempoMeta: "70 a 85 min",
    criterioDominio: "80% no quiz + 2 leituras corretas de gráfico/tira",
    blocoCronometrado: null,
    revisao24hDe: 23,
    revisaoSemanal: false,
    revisaoCumulativa: "retoma desconto, acréscimo e coesão",
    cadernoDeErrosObrigatorio: true,
    prioridadeAprovacao: "alta"
  },
  {
    numero: 25,
    data: "2026-04-24",
    semana: 5,
    fase: "fase-2-consolidacao-aceleracao",
    titulo: "Revisão da Semana 5 + Desafio Misto 5",
    disciplina: "Português + Matemática",
    disciplinaNome: "Português + Matemática",
    disciplinaIcone: "⚔️",
    reino: "Reino da Agilidade",
    reinoIcone: "🧮",
    expansao: "Semana do cotidiano de prova com bloco misto mais fiel ao vestibulinho.",
    raridade: "raro",
    xp: 15,
    moedas: 5,
    arquivo: "apostilas/dia-025.html",
    iconeMissao: "🎯",
    funcaoPedagogica: "checkpoint_contextual",
    habilidadePrincipal: "resolver situações de vida real com leitura e matemática integradas",
    habilidadeSecundaria: "mapear erro em contexto, porcentagem, gráfico e comando",
    focoDeProva: "ler situação real sem se perder em excesso de informação",
    tempoMeta: "80 a 90 min",
    criterioDominio: "75% no bloco misto + análise dos 3 erros mais caros",
    blocoCronometrado: {
      ativo: true,
      duracaoMin: 15,
      objetivo: "checkpoint de contexto e dados"
    },
    revisao24hDe: 24,
    revisaoSemanal: true,
    revisaoCumulativa: "sintetiza Semana 5 + resgata habilidade mais fraca da Semana 4",
    cadernoDeErrosObrigatorio: true,
    prioridadeAprovacao: "alta"
  },
  {
    numero: 26,
    data: "2026-04-27",
    semana: 6,
    fase: "fase-2-consolidacao-aceleracao",
    titulo: "Humor, Ironia e Intenção + Perímetro",
    disciplina: "Português + Matemática",
    disciplinaNome: "Português + Matemática",
    disciplinaIcone: "⚔️",
    reino: "Reino da Agilidade",
    reinoIcone: "🧮",
    expansao: "Sentido não literal e contorno de figuras.",
    raridade: "comum",
    xp: 10,
    moedas: 3,
    arquivo: "apostilas/dia-026.html",
    iconeMissao: "⚔️",
    funcaoPedagogica: "leitura_maliciosa",
    habilidadePrincipal: "perceber humor, ironia e intenção sem cair na leitura literal",
    habilidadeSecundaria: "calcular perímetro com desenho e unidade",
    focoDeProva: "não marcar a alternativa literal quando o texto quer efeito",
    tempoMeta: "70 a 85 min",
    criterioDominio: "80% no quiz + 2 itens de intenção + 2 perímetros corretos",
    blocoCronometrado: null,
    revisao24hDe: 25,
    revisaoSemanal: false,
    revisaoCumulativa: "retoma gráfico/tabela e contexto",
    cadernoDeErrosObrigatorio: true,
    prioridadeAprovacao: "alta"
  },
  {
    numero: 27,
    data: "2026-04-28",
    semana: 6,
    fase: "fase-2-consolidacao-aceleracao",
    titulo: "Vocabulário no Contexto + Área de Figuras",
    disciplina: "Português + Matemática",
    disciplinaNome: "Português + Matemática",
    disciplinaIcone: "⚔️",
    reino: "Reino da Agilidade",
    reinoIcone: "🧮",
    expansao: "Palavra depende do contexto e cálculo de área.",
    raridade: "comum",
    xp: 10,
    moedas: 3,
    arquivo: "apostilas/dia-027.html",
    iconeMissao: "⚔️",
    funcaoPedagogica: "leitura_maliciosa",
    habilidadePrincipal: "determinar significado da palavra pelo contexto",
    habilidadeSecundaria: "calcular área de figuras planas simples",
    focoDeProva: "não escolher significado automático sem olhar a frase",
    tempoMeta: "70 a 85 min",
    criterioDominio: "80% no quiz + 2 itens de vocabulário contextual + 2 áreas corretas",
    blocoCronometrado: null,
    revisao24hDe: 26,
    revisaoSemanal: false,
    revisaoCumulativa: "retoma humor e perímetro",
    cadernoDeErrosObrigatorio: true,
    prioridadeAprovacao: "alta"
  },
  {
    numero: 28,
    data: "2026-04-29",
    semana: 6,
    fase: "fase-2-consolidacao-aceleracao",
    titulo: "Reescrita com Sentido + Geometria Plana",
    disciplina: "Português + Matemática",
    disciplinaNome: "Português + Matemática",
    disciplinaIcone: "⚔️",
    reino: "Reino da Agilidade",
    reinoIcone: "🧮",
    expansao: "Trocar palavras sem perder ideia e reconhecer formas planas.",
    raridade: "comum",
    xp: 10,
    moedas: 3,
    arquivo: "apostilas/dia-028.html",
    iconeMissao: "⚔️",
    funcaoPedagogica: "leitura_maliciosa",
    habilidadePrincipal: "reescrever preservando sentido central",
    habilidadeSecundaria: "identificar propriedades básicas de figuras planas",
    focoDeProva: "não trocar palavra e alterar o sentido sem perceber",
    tempoMeta: "70 a 85 min",
    criterioDominio: "80% no quiz + 1 reescrita válida + 3 identificações geométricas",
    blocoCronometrado: {
      ativo: true,
      duracaoMin: 6,
      objetivo: "comparar alternativas próximas de reescrita"
    },
    revisao24hDe: 27,
    revisaoSemanal: false,
    revisaoCumulativa: "retoma vocabulário contextual",
    cadernoDeErrosObrigatorio: true,
    prioridadeAprovacao: "alta"
  },
  {
    numero: 29,
    data: "2026-04-30",
    semana: 6,
    fase: "fase-2-consolidacao-aceleracao",
    titulo: "Problemas em Dois Passos + Sólidos Geométricos",
    disciplina: "Português + Matemática",
    disciplinaNome: "Português + Matemática",
    disciplinaIcone: "⚔️",
    reino: "Reino da Agilidade",
    reinoIcone: "🧮",
    expansao: "Planejar conta em sequência e reconhecer sólidos geométricos.",
    raridade: "comum",
    xp: 10,
    moedas: 3,
    arquivo: "apostilas/dia-029.html",
    iconeMissao: "⚔️",
    funcaoPedagogica: "leitura_maliciosa",
    habilidadePrincipal: "organizar problema em duas etapas sem pular informação",
    habilidadeSecundaria: "reconhecer sólidos e suas características iniciais",
    focoDeProva: "não resolver só a primeira etapa e parar",
    tempoMeta: "70 a 85 min",
    criterioDominio: "80% no quiz + 2 problemas em dois passos + 3 sólidos identificados",
    blocoCronometrado: null,
    revisao24hDe: 28,
    revisaoSemanal: false,
    revisaoCumulativa: "retoma geometria plana",
    cadernoDeErrosObrigatorio: true,
    prioridadeAprovacao: "alta"
  },
  {
    numero: 30,
    data: "2026-05-01",
    semana: 6,
    fase: "fase-2-consolidacao-aceleracao",
    titulo: "Revisão da Semana 6 + Desafio Misto 6",
    disciplina: "Português + Matemática",
    disciplinaNome: "Português + Matemática",
    disciplinaIcone: "⚔️",
    reino: "Reino da Agilidade",
    reinoIcone: "🧮",
    expansao: "Primeiro checkpoint com alternativas mais próximas, humor, geometria e dois passos.",
    raridade: "raro",
    xp: 15,
    moedas: 5,
    arquivo: "apostilas/dia-030.html",
    iconeMissao: "🎯",
    funcaoPedagogica: "checkpoint_de_pegadinha",
    habilidadePrincipal: "distinguir alternativa correta entre opções parecidas",
    habilidadeSecundaria: "registrar erros por literalidade, distração e forma",
    focoDeProva: "não cair na primeira opção que parece boa",
    tempoMeta: "80 a 90 min",
    criterioDominio: "75% no bloco misto + caderno de erros com causa do erro",
    blocoCronometrado: {
      ativo: true,
      duracaoMin: 15,
      objetivo: "checkpoint com pegadinhas controladas"
    },
    revisao24hDe: 29,
    revisaoSemanal: true,
    revisaoCumulativa: "sintetiza Semana 6 + resgata porcentagem ou gráfico conforme erro",
    cadernoDeErrosObrigatorio: true,
    prioridadeAprovacao: "alta"
  },
  {
    numero: 31,
    data: "2026-05-04",
    semana: 7,
    fase: "fase-3-ponte-6ano",
    titulo: "Comparação entre Textos + Operações Combinadas",
    disciplina: "Português + Matemática",
    disciplinaNome: "Português + Matemática",
    disciplinaIcone: "⚔️",
    reino: "Reino da Estratégia",
    reinoIcone: "🏹",
    expansao: "Cruzar informações entre textos e organizar ordem de resolução.",
    raridade: "incomum",
    xp: 12,
    moedas: 4,
    arquivo: "apostilas/dia-031.html",
    iconeMissao: "⚔️",
    funcaoPedagogica: "ponte_de_complexidade",
    habilidadePrincipal: "comparar duas fontes sem misturar informação",
    habilidadeSecundaria: "resolver operações combinadas com ordem clara",
    focoDeProva: "não responder olhando só um texto ou só um trecho",
    tempoMeta: "75 a 90 min",
    criterioDominio: "80% no quiz + 2 comparações corretas + 2 operações combinadas",
    blocoCronometrado: {
      ativo: true,
      duracaoMin: 8,
      objetivo: "primeira mini prova curta"
    },
    revisao24hDe: 30,
    revisaoSemanal: false,
    revisaoCumulativa: "retoma alternativas próximas",
    cadernoDeErrosObrigatorio: true,
    prioridadeAprovacao: "alta"
  },
  {
    numero: 32,
    data: "2026-05-05",
    semana: 7,
    fase: "fase-3-ponte-6ano",
    titulo: "Tese, Opinião e Fato + Problemas Longos",
    disciplina: "Português + Matemática",
    disciplinaNome: "Português + Matemática",
    disciplinaIcone: "⚔️",
    reino: "Reino da Estratégia",
    reinoIcone: "🏹",
    expansao: "Separar opinião de informação e sustentar atenção em enunciados maiores.",
    raridade: "incomum",
    xp: 12,
    moedas: 4,
    arquivo: "apostilas/dia-032.html",
    iconeMissao: "⚔️",
    funcaoPedagogica: "ponte_de_complexidade",
    habilidadePrincipal: "distinguir tese, opinião e fato em texto mais denso",
    habilidadeSecundaria: "sustentar leitura em problema longo sem perder o alvo",
    focoDeProva: "não cansar e responder metade do problema",
    tempoMeta: "75 a 90 min",
    criterioDominio: "80% no quiz + 1 tese justificada + 2 problemas longos corretos",
    blocoCronometrado: null,
    revisao24hDe: 31,
    revisaoSemanal: false,
    revisaoCumulativa: "retoma comparação entre textos",
    cadernoDeErrosObrigatorio: true,
    prioridadeAprovacao: "alta"
  },
  {
    numero: 33,
    data: "2026-05-06",
    semana: 7,
    fase: "fase-3-ponte-6ano",
    titulo: "Informações Cruzadas + Decimais em Problemas",
    disciplina: "Português + Matemática",
    disciplinaNome: "Português + Matemática",
    disciplinaIcone: "⚔️",
    reino: "Reino da Estratégia",
    reinoIcone: "🏹",
    expansao: "Buscar relação entre pistas e aplicar decimais em contexto.",
    raridade: "incomum",
    xp: 12,
    moedas: 4,
    arquivo: "apostilas/dia-033.html",
    iconeMissao: "⚔️",
    funcaoPedagogica: "ponte_de_complexidade",
    habilidadePrincipal: "cruzar pistas de mais de uma frase ou fonte",
    habilidadeSecundaria: "aplicar decimais em situações compostas",
    focoDeProva: "não usar pista isolada quando a resposta exige duas",
    tempoMeta: "75 a 90 min",
    criterioDominio: "80% no quiz + 2 cruzamentos corretos + 2 problemas com decimais",
    blocoCronometrado: null,
    revisao24hDe: 32,
    revisaoSemanal: false,
    revisaoCumulativa: "retoma tese/opinião/fato",
    cadernoDeErrosObrigatorio: true,
    prioridadeAprovacao: "alta"
  },
  {
    numero: 34,
    data: "2026-05-07",
    semana: 7,
    fase: "fase-3-ponte-6ano",
    titulo: "Dicas do Enunciado + Frações e Decimais",
    disciplina: "Português + Matemática",
    disciplinaNome: "Português + Matemática",
    disciplinaIcone: "⚔️",
    reino: "Reino da Estratégia",
    reinoIcone: "🏹",
    expansao: "Palavras-chave do comando e ponte entre fração e decimal.",
    raridade: "incomum",
    xp: 12,
    moedas: 4,
    arquivo: "apostilas/dia-034.html",
    iconeMissao: "⚔️",
    funcaoPedagogica: "ponte_de_complexidade",
    habilidadePrincipal: "usar palavras do enunciado como pista para a estratégia",
    habilidadeSecundaria: "ligar fração e decimal na mesma situação",
    focoDeProva: "não ignorar a pista do comando quando a conta parece óbvia",
    tempoMeta: "75 a 90 min",
    criterioDominio: "80% no quiz + questão-âncora de comando + ponte fração/decimal",
    blocoCronometrado: {
      ativo: true,
      duracaoMin: 8,
      objetivo: "responder por pista de comando sob tempo"
    },
    revisao24hDe: 33,
    revisaoSemanal: false,
    revisaoCumulativa: "retoma cruzamento de informações",
    cadernoDeErrosObrigatorio: true,
    prioridadeAprovacao: "alta"
  },
  {
    numero: 35,
    data: "2026-05-08",
    semana: 7,
    fase: "fase-3-ponte-6ano",
    titulo: "Revisão da Semana 7 + Desafio Misto 7",
    disciplina: "Português + Matemática",
    disciplinaNome: "Português + Matemática",
    disciplinaIcone: "⚔️",
    reino: "Reino da Estratégia",
    reinoIcone: "🏹",
    expansao: "Checkpoint com mini prova curta, textos mais densos e problemas longos.",
    raridade: "raro",
    xp: 15,
    moedas: 5,
    arquivo: "apostilas/dia-035.html",
    iconeMissao: "🎯",
    funcaoPedagogica: "checkpoint_de_resistencia",
    habilidadePrincipal: "sustentar atenção em blocos com mais densidade",
    habilidadeSecundaria: "detectar se o erro veio de cansaço, leitura ou cálculo",
    focoDeProva: "não perder precisão quando o enunciado cresce",
    tempoMeta: "80 a 90 min",
    criterioDominio: "75% no bloco + análise do padrão de erro por fadiga",
    blocoCronometrado: {
      ativo: true,
      duracaoMin: 18,
      objetivo: "mini prova de resistência"
    },
    revisao24hDe: 34,
    revisaoSemanal: true,
    revisaoCumulativa: "sintetiza Semana 7 + resgata maior erro da base",
    cadernoDeErrosObrigatorio: true,
    prioridadeAprovacao: "alta"
  },
  {
    numero: 36,
    data: "2026-05-11",
    semana: 8,
    fase: "fase-3-ponte-6ano",
    titulo: "Reescrita Inteligente + Razão Simples",
    disciplina: "Português + Matemática",
    disciplinaNome: "Português + Matemática",
    disciplinaIcone: "⚔️",
    reino: "Reino da Estratégia",
    reinoIcone: "🏹",
    expansao: "Mudar forma, manter sentido e comparar proporcionalmente.",
    raridade: "incomum",
    xp: 12,
    moedas: 4,
    arquivo: "apostilas/dia-036.html",
    iconeMissao: "⚔️",
    funcaoPedagogica: "eliminacao_de_alternativas",
    habilidadePrincipal: "comparar versões reescritas sem perder o sentido original",
    habilidadeSecundaria: "entender razão simples em contexto",
    focoDeProva: "não escolher alternativa elegante mas semanticamente errada",
    tempoMeta: "75 a 90 min",
    criterioDominio: "80% no quiz + 2 reescritas corretas + 2 razões simples",
    blocoCronometrado: null,
    revisao24hDe: 35,
    revisaoSemanal: false,
    revisaoCumulativa: "retoma resistência e comando",
    cadernoDeErrosObrigatorio: true,
    prioridadeAprovacao: "alta"
  },
  {
    numero: 37,
    data: "2026-05-12",
    semana: 8,
    fase: "fase-3-ponte-6ano",
    titulo: "Coerência e Contradição + Escalas e Proporção",
    disciplina: "Português + Matemática",
    disciplinaNome: "Português + Matemática",
    disciplinaIcone: "⚔️",
    reino: "Reino da Estratégia",
    reinoIcone: "🏹",
    expansao: "Detectar incoerência e trabalhar escala.",
    raridade: "incomum",
    xp: 12,
    moedas: 4,
    arquivo: "apostilas/dia-037.html",
    iconeMissao: "⚔️",
    funcaoPedagogica: "eliminacao_de_alternativas",
    habilidadePrincipal: "enxergar contradição ou incoerência entre partes do texto",
    habilidadeSecundaria: "usar escala e proporção em situações visuais",
    focoDeProva: "não aceitar alternativa internamente incoerente",
    tempoMeta: "75 a 90 min",
    criterioDominio: "80% no quiz + 2 incoerências detectadas + 2 escalas resolvidas",
    blocoCronometrado: null,
    revisao24hDe: 36,
    revisaoSemanal: false,
    revisaoCumulativa: "retoma reescrita e razão",
    cadernoDeErrosObrigatorio: true,
    prioridadeAprovacao: "alta"
  },
  {
    numero: 38,
    data: "2026-05-13",
    semana: 8,
    fase: "fase-3-ponte-6ano",
    titulo: "Leitura de Dados + Média Inicial",
    disciplina: "Português + Matemática",
    disciplinaNome: "Português + Matemática",
    disciplinaIcone: "⚔️",
    reino: "Reino da Estratégia",
    reinoIcone: "🏹",
    expansao: "Tabelas e gráficos com média aritmética intuitiva.",
    raridade: "incomum",
    xp: 12,
    moedas: 4,
    arquivo: "apostilas/dia-038.html",
    iconeMissao: "⚔️",
    funcaoPedagogica: "eliminacao_de_alternativas",
    habilidadePrincipal: "extrair e combinar dados de tabela e gráfico",
    habilidadeSecundaria: "calcular média aritmética simples com sentido",
    focoDeProva: "não pegar só um dado e esquecer o conjunto",
    tempoMeta: "75 a 90 min",
    criterioDominio: "80% no quiz + 2 leituras de dados + 2 médias corretas",
    blocoCronometrado: {
      ativo: true,
      duracaoMin: 8,
      objetivo: "dados e média com tempo controlado"
    },
    revisao24hDe: 37,
    revisaoSemanal: false,
    revisaoCumulativa: "retoma coerência e proporção",
    cadernoDeErrosObrigatorio: true,
    prioridadeAprovacao: "alta"
  },
  {
    numero: 39,
    data: "2026-05-14",
    semana: 8,
    fase: "fase-3-ponte-6ano",
    titulo: "Estratégia de Alternativas + Tabelas Complexas",
    disciplina: "Português + Matemática",
    disciplinaNome: "Português + Matemática",
    disciplinaIcone: "⚔️",
    reino: "Reino da Estratégia",
    reinoIcone: "🏹",
    expansao: "Eliminar opção ruim e interpretar dados mais densos.",
    raridade: "incomum",
    xp: 12,
    moedas: 4,
    arquivo: "apostilas/dia-039.html",
    iconeMissao: "⚔️",
    funcaoPedagogica: "eliminacao_de_alternativas",
    habilidadePrincipal: "eliminar alternativas por critério e não por sensação",
    habilidadeSecundaria: "interpretar tabelas mais densas com organização",
    focoDeProva: "chute diminui quando a eliminação melhora",
    tempoMeta: "75 a 90 min",
    criterioDominio: "80% no quiz + justificar eliminação em 2 itens",
    blocoCronometrado: null,
    revisao24hDe: 38,
    revisaoSemanal: false,
    revisaoCumulativa: "retoma leitura de dados",
    cadernoDeErrosObrigatorio: true,
    prioridadeAprovacao: "alta"
  },
  {
    numero: 40,
    data: "2026-05-15",
    semana: 8,
    fase: "fase-3-ponte-6ano",
    titulo: "Revisão da Semana 8 + Desafio Misto 8",
    disciplina: "Português + Matemática",
    disciplinaNome: "Português + Matemática",
    disciplinaIcone: "⚔️",
    reino: "Reino da Estratégia",
    reinoIcone: "🏹",
    expansao: "Checkpoint com alternativas parecidas, dados densos e proporcionalidade.",
    raridade: "raro",
    xp: 15,
    moedas: 5,
    arquivo: "apostilas/dia-040.html",
    iconeMissao: "🎯",
    funcaoPedagogica: "checkpoint_de_escolha",
    habilidadePrincipal: "escolher melhor entre alternativas próximas",
    habilidadeSecundaria: "identificar se o erro foi de leitura, coerência ou dado",
    focoDeProva: "substituir chute por critério",
    tempoMeta: "80 a 90 min",
    criterioDominio: "75% no bloco + justificativa de eliminação em pelo menos 2 itens",
    blocoCronometrado: {
      ativo: true,
      duracaoMin: 18,
      objetivo: "mini prova de escolha entre alternativas"
    },
    revisao24hDe: 39,
    revisaoSemanal: true,
    revisaoCumulativa: "sintetiza Semana 8 + resgata problema mais caro da Semana 7",
    cadernoDeErrosObrigatorio: true,
    prioridadeAprovacao: "alta"
  },
  {
    numero: 41,
    data: "2026-05-18",
    semana: 9,
    fase: "fase-3-ponte-6ano",
    titulo: "Efeito de Sentido + Porcentagem em Problemas",
    disciplina: "Português + Matemática",
    disciplinaNome: "Português + Matemática",
    disciplinaIcone: "⚔️",
    reino: "Reino da Estratégia",
    reinoIcone: "🏹",
    expansao: "Tom, intenção, escolha vocabular e porcentagem em contexto.",
    raridade: "incomum",
    xp: 12,
    moedas: 4,
    arquivo: "apostilas/dia-041.html",
    iconeMissao: "⚔️",
    funcaoPedagogica: "pressao_controlada",
    habilidadePrincipal: "perceber efeito de sentido sem se prender ao literal",
    habilidadeSecundaria: "aplicar porcentagem em problema contextualizado",
    focoDeProva: "não trocar tom por informação literal",
    tempoMeta: "75 a 90 min",
    criterioDominio: "80% no quiz + 2 efeitos de sentido + 2 porcentagens em contexto",
    blocoCronometrado: null,
    revisao24hDe: 40,
    revisaoSemanal: false,
    revisaoCumulativa: "retoma alternativas e coerência",
    cadernoDeErrosObrigatorio: true,
    prioridadeAprovacao: "alta"
  },
  {
    numero: 42,
    data: "2026-05-19",
    semana: 9,
    fase: "fase-3-ponte-6ano",
    titulo: "Texto Verbal e Não Verbal + Unidades de Tempo",
    disciplina: "Português + Matemática",
    disciplinaNome: "Português + Matemática",
    disciplinaIcone: "⚔️",
    reino: "Reino da Estratégia",
    reinoIcone: "🏹",
    expansao: "Ler imagem e texto juntos, com tempo e calendário.",
    raridade: "incomum",
    xp: 12,
    moedas: 4,
    arquivo: "apostilas/dia-042.html",
    iconeMissao: "⚔️",
    funcaoPedagogica: "pressao_controlada",
    habilidadePrincipal: "integrar informação verbal e visual",
    habilidadeSecundaria: "resolver tempo, duração e calendário",
    focoDeProva: "não ler só o desenho nem só a legenda",
    tempoMeta: "75 a 90 min",
    criterioDominio: "80% no quiz + 2 integrações verbo-visuais + 2 questões de tempo",
    blocoCronometrado: null,
    revisao24hDe: 41,
    revisaoSemanal: false,
    revisaoCumulativa: "retoma efeito de sentido",
    cadernoDeErrosObrigatorio: true,
    prioridadeAprovacao: "alta"
  },
  {
    numero: 43,
    data: "2026-05-20",
    semana: 9,
    fase: "fase-3-ponte-6ano",
    titulo: "Pegadinhas de Leitura + Medidas e Conversões",
    disciplina: "Português + Matemática",
    disciplinaNome: "Português + Matemática",
    disciplinaIcone: "⚔️",
    reino: "Reino da Estratégia",
    reinoIcone: "🏹",
    expansao: "Treino para não cair em detalhe enganoso e conversões de medida.",
    raridade: "incomum",
    xp: 12,
    moedas: 4,
    arquivo: "apostilas/dia-043.html",
    iconeMissao: "⚔️",
    funcaoPedagogica: "pressao_controlada",
    habilidadePrincipal: "identificar pegadinha de leitura por palavra ou detalhe",
    habilidadeSecundaria: "converter medidas sem perder unidade",
    focoDeProva: "ler inteiro antes de marcar",
    tempoMeta: "75 a 90 min",
    criterioDominio: "80% no quiz + 2 pegadinhas evitadas + 2 conversões corretas",
    blocoCronometrado: {
      ativo: true,
      duracaoMin: 8,
      objetivo: "ler e converter sem tropeço"
    },
    revisao24hDe: 42,
    revisaoSemanal: false,
    revisaoCumulativa: "retoma verbal e não verbal",
    cadernoDeErrosObrigatorio: true,
    prioridadeAprovacao: "alta"
  },
  {
    numero: 44,
    data: "2026-05-21",
    semana: 9,
    fase: "fase-3-ponte-6ano",
    titulo: "Alternativa Correta sem Chute + Geometria Aplicada",
    disciplina: "Português + Matemática",
    disciplinaNome: "Português + Matemática",
    disciplinaIcone: "⚔️",
    reino: "Reino da Estratégia",
    reinoIcone: "🏹",
    expansao: "Escolha estratégica e uso da geometria em problemas.",
    raridade: "incomum",
    xp: 12,
    moedas: 4,
    arquivo: "apostilas/dia-044.html",
    iconeMissao: "⚔️",
    funcaoPedagogica: "pressao_controlada",
    habilidadePrincipal: "chegar à alternativa correta por eliminação e evidência",
    habilidadeSecundaria: "aplicar geometria em contexto real",
    focoDeProva: "trocar confiança vazia por procedimento",
    tempoMeta: "75 a 90 min",
    criterioDominio: "80% no quiz + justificar a escolha em 2 itens",
    blocoCronometrado: null,
    revisao24hDe: 43,
    revisaoSemanal: false,
    revisaoCumulativa: "retoma medidas e pegadinhas",
    cadernoDeErrosObrigatorio: true,
    prioridadeAprovacao: "alta"
  },
  {
    numero: 45,
    data: "2026-05-22",
    semana: 9,
    fase: "fase-3-ponte-6ano",
    titulo: "Revisão da Semana 9 + Desafio Misto 9",
    disciplina: "Português + Matemática",
    disciplinaNome: "Português + Matemática",
    disciplinaIcone: "⚔️",
    reino: "Reino da Estratégia",
    reinoIcone: "🏹",
    expansao: "Checkpoint com dois blocos sob tempo, integrando leitura fina e matemática aplicada.",
    raridade: "raro",
    xp: 15,
    moedas: 5,
    arquivo: "apostilas/dia-045.html",
    iconeMissao: "🎯",
    funcaoPedagogica: "checkpoint_sob_pressao",
    habilidadePrincipal: "controlar detalhe, pegadinha e ritmo em blocos curtos",
    habilidadeSecundaria: "medir estabilidade antes dos simulados formais",
    focoDeProva: "não se desorganizar quando o tempo aperta",
    tempoMeta: "80 a 90 min",
    criterioDominio: "75% no bloco + registro do erro mais recorrente e do mais evitável",
    blocoCronometrado: {
      ativo: true,
      duracaoMin: 20,
      objetivo: "dois blocos sob tempo antes da arena de simulados"
    },
    revisao24hDe: 44,
    revisaoSemanal: true,
    revisaoCumulativa: "sintetiza Semana 9 + resgata maior falha das Semanas 7 e 8",
    cadernoDeErrosObrigatorio: true,
    prioridadeAprovacao: "alta"
  },
  {
    numero: 46,
    data: "2026-05-25",
    semana: 10,
    fase: "fase-4-dominio-hibrido",
    titulo: "Mini Simulado 1 — Bloco A",
    disciplina: "Simulado",
    disciplinaNome: "Simulado",
    disciplinaIcone: "🏆",
    reino: "Reino dos Simulados",
    reinoIcone: "⚔️",
    expansao: "Primeiro bloco formal de simulado misto em formato de prova.",
    raridade: "raro",
    xp: 15,
    moedas: 5,
    arquivo: "apostilas/dia-046.html",
    iconeMissao: "🏆",
    funcaoPedagogica: "simulado",
    habilidadePrincipal: "medir desempenho real em Português e Matemática misturados",
    habilidadeSecundaria: "observar comportamento sob tempo e pressão",
    focoDeProva: "medir antes de corrigir",
    tempoMeta: "60 a 75 min",
    criterioDominio: "aplicar simulado inteiro e registrar tempo por bloco",
    blocoCronometrado: {
      ativo: true,
      duracaoMin: 30,
      objetivo: "simulado formal bloco A"
    },
    revisao24hDe: 45,
    revisaoSemanal: false,
    revisaoCumulativa: "puxa conteúdos mais frágeis da Semana 9",
    cadernoDeErrosObrigatorio: true,
    prioridadeAprovacao: "alta"
  },
  {
    numero: 47,
    data: "2026-05-26",
    semana: 10,
    fase: "fase-4-dominio-hibrido",
    titulo: "Correção Guiada do Simulado 1",
    disciplina: "Correção Estratégica",
    disciplinaNome: "Correção Estratégica",
    disciplinaIcone: "🧠",
    reino: "Reino dos Simulados",
    reinoIcone: "⚔️",
    expansao: "Análise dos erros, por que errou e como evitar repetir.",
    raridade: "incomum",
    xp: 12,
    moedas: 4,
    arquivo: "apostilas/dia-047.html",
    iconeMissao: "🧠",
    funcaoPedagogica: "correcao_estrategica",
    habilidadePrincipal: "classificar o erro por causa real",
    habilidadeSecundaria: "transformar erro em regra de correção",
    focoDeProva: "correção não é gabarito, é diagnóstico",
    tempoMeta: "60 a 75 min",
    criterioDominio: "todo erro relevante classificado com ação de reparo",
    blocoCronometrado: null,
    revisao24hDe: 46,
    revisaoSemanal: false,
    revisaoCumulativa: "retoma apenas habilidades erradas no simulado",
    cadernoDeErrosObrigatorio: true,
    prioridadeAprovacao: "alta"
  },
  {
    numero: 48,
    data: "2026-05-27",
    semana: 10,
    fase: "fase-4-dominio-hibrido",
    titulo: "Mini Simulado 1 — Bloco B",
    disciplina: "Simulado",
    disciplinaNome: "Simulado",
    disciplinaIcone: "🏆",
    reino: "Reino dos Simulados",
    reinoIcone: "⚔️",
    expansao: "Novo bloco com controle de tempo e autonomia maior.",
    raridade: "raro",
    xp: 15,
    moedas: 5,
    arquivo: "apostilas/dia-048.html",
    iconeMissao: "🏆",
    funcaoPedagogica: "simulado",
    habilidadePrincipal: "medir ganho imediato após correção",
    habilidadeSecundaria: "sustentar concentração em segundo bloco",
    focoDeProva: "reaplicar sob nova pressão",
    tempoMeta: "60 a 75 min",
    criterioDominio: "comparar desempenho com o bloco A",
    blocoCronometrado: {
      ativo: true,
      duracaoMin: 30,
      objetivo: "simulado formal bloco B"
    },
    revisao24hDe: 47,
    revisaoSemanal: false,
    revisaoCumulativa: "retoma erros corrigidos",
    cadernoDeErrosObrigatorio: true,
    prioridadeAprovacao: "alta"
  },
  {
    numero: 49,
    data: "2026-05-28",
    semana: 10,
    fase: "fase-4-dominio-hibrido",
    titulo: "Correção Guiada + Reensino",
    disciplina: "Correção Estratégica",
    disciplinaNome: "Correção Estratégica",
    disciplinaIcone: "🧠",
    reino: "Reino dos Simulados",
    reinoIcone: "⚔️",
    expansao: "Retomar lacunas e reensinar o ponto fraco detectado.",
    raridade: "incomum",
    xp: 12,
    moedas: 4,
    arquivo: "apostilas/dia-049.html",
    iconeMissao: "🧠",
    funcaoPedagogica: "recuperacao_de_erros",
    habilidadePrincipal: "reensinar o topo 3 de erros mais caros",
    habilidadeSecundaria: "produzir mini treino de reparo",
    focoDeProva: "não revisar tudo, só o que mais derruba",
    tempoMeta: "60 a 75 min",
    criterioDominio: "fechar 3 erros prioritários com mini treino de reparo",
    blocoCronometrado: null,
    revisao24hDe: 48,
    revisaoSemanal: false,
    revisaoCumulativa: "puxa apenas lacunas do simulado 1",
    cadernoDeErrosObrigatorio: true,
    prioridadeAprovacao: "alta"
  },
  {
    numero: 50,
    data: "2026-05-29",
    semana: 10,
    fase: "fase-4-dominio-hibrido",
    titulo: "Revisão da Semana 10 + Desafio Misto 10",
    disciplina: "Domínio de Prova",
    disciplinaNome: "Domínio de Prova",
    disciplinaIcone: "⚔️",
    reino: "Reino dos Simulados",
    reinoIcone: "⚔️",
    expansao: "Bloco curto de consolidação pós-simulado com foco no que mais derrubou.",
    raridade: "raro",
    xp: 15,
    moedas: 5,
    arquivo: "apostilas/dia-050.html",
    iconeMissao: "🎯",
    funcaoPedagogica: "consolidacao_pos_simulado",
    habilidadePrincipal: "fixar correções de maior impacto",
    habilidadeSecundaria: "medir se o erro reaparece em bloco curto",
    focoDeProva: "converter correção em acerto",
    tempoMeta: "60 a 75 min",
    criterioDominio: "75% no bloco curto + queda do erro recorrente",
    blocoCronometrado: {
      ativo: true,
      duracaoMin: 12,
      objetivo: "consolidacao pós-simulado"
    },
    revisao24hDe: 49,
    revisaoSemanal: true,
    revisaoCumulativa: "sintetiza Semana 10",
    cadernoDeErrosObrigatorio: true,
    prioridadeAprovacao: "alta"
  },
  {
    numero: 51,
    data: "2026-06-01",
    semana: 11,
    fase: "fase-4-dominio-hibrido",
    titulo: "Mini Simulado 2 — Bloco A",
    disciplina: "Simulado",
    disciplinaNome: "Simulado",
    disciplinaIcone: "🏆",
    reino: "Reino dos Simulados",
    reinoIcone: "⚔️",
    expansao: "Novo ciclo de prova com foco em consistência.",
    raridade: "raro",
    xp: 15,
    moedas: 5,
    arquivo: "apostilas/dia-051.html",
    iconeMissao: "🏆",
    funcaoPedagogica: "simulado",
    habilidadePrincipal: "medir estabilidade após semana 10",
    habilidadeSecundaria: "controlar ansiedade e ritmo",
    focoDeProva: "oscilar menos do que no simulado 1",
    tempoMeta: "60 a 75 min",
    criterioDominio: "aplicar e comparar com mini simulado 1",
    blocoCronometrado: {
      ativo: true,
      duracaoMin: 30,
      objetivo: "simulado 2 bloco A"
    },
    revisao24hDe: 50,
    revisaoSemanal: false,
    revisaoCumulativa: "puxa top erros do simulado 1",
    cadernoDeErrosObrigatorio: true,
    prioridadeAprovacao: "alta"
  },
  {
    numero: 52,
    data: "2026-06-02",
    semana: 11,
    fase: "fase-4-dominio-hibrido",
    titulo: "Correção com Estratégia de Prova",
    disciplina: "Correção Estratégica",
    disciplinaNome: "Correção Estratégica",
    disciplinaIcone: "🧠",
    reino: "Reino dos Simulados",
    reinoIcone: "⚔️",
    expansao: "Treino de leitura do comando, gestão da pressão e análise dos erros.",
    raridade: "incomum",
    xp: 12,
    moedas: 4,
    arquivo: "apostilas/dia-052.html",
    iconeMissao: "🧠",
    funcaoPedagogica: "correcao_estrategica",
    habilidadePrincipal: "separar erro de conteúdo de erro de procedimento",
    habilidadeSecundaria: "revisar comando e gestão da pressão",
    focoDeProva: "descobrir o que o aluno sabe mas não converte",
    tempoMeta: "60 a 75 min",
    criterioDominio: "todo erro relevante classificado como conteúdo, atenção, tempo ou comando",
    blocoCronometrado: null,
    revisao24hDe: 51,
    revisaoSemanal: false,
    revisaoCumulativa: "puxa apenas erros vivos do simulado 2",
    cadernoDeErrosObrigatorio: true,
    prioridadeAprovacao: "alta"
  },
  {
    numero: 53,
    data: "2026-06-03",
    semana: 11,
    fase: "fase-4-dominio-hibrido",
    titulo: "Mini Simulado 2 — Bloco B",
    disciplina: "Simulado",
    disciplinaNome: "Simulado",
    disciplinaIcone: "🏆",
    reino: "Reino dos Simulados",
    reinoIcone: "⚔️",
    expansao: "Mais um bloco cronometrado para estabilizar desempenho.",
    raridade: "raro",
    xp: 15,
    moedas: 5,
    arquivo: "apostilas/dia-053.html",
    iconeMissao: "🏆",
    funcaoPedagogica: "simulado",
    habilidadePrincipal: "testar consistência no segundo bloco",
    habilidadeSecundaria: "aplicar correção imediatamente",
    focoDeProva: "diminuir erro repetido entre bloco A e B",
    tempoMeta: "60 a 75 min",
    criterioDominio: "reduzir erro repetido em relação ao bloco A",
    blocoCronometrado: {
      ativo: true,
      duracaoMin: 30,
      objetivo: "simulado 2 bloco B"
    },
    revisao24hDe: 52,
    revisaoSemanal: false,
    revisaoCumulativa: "retoma pontos fracos do bloco A",
    cadernoDeErrosObrigatorio: true,
    prioridadeAprovacao: "alta"
  },
  {
    numero: 54,
    data: "2026-06-04",
    semana: 11,
    fase: "fase-4-dominio-hibrido",
    titulo: "Correção Guiada + Recuperação de Erros",
    disciplina: "Correção Estratégica",
    disciplinaNome: "Correção Estratégica",
    disciplinaIcone: "🧠",
    reino: "Reino dos Simulados",
    reinoIcone: "⚔️",
    expansao: "Ajuste fino dos erros insistentes.",
    raridade: "incomum",
    xp: 12,
    moedas: 4,
    arquivo: "apostilas/dia-054.html",
    iconeMissao: "🧠",
    funcaoPedagogica: "recuperacao_de_erros",
    habilidadePrincipal: "atacar os erros que insistem mesmo após correção",
    habilidadeSecundaria: "fechar protocolos pessoais de revisão",
    focoDeProva: "o erro recorrente vira prioridade absoluta",
    tempoMeta: "60 a 75 min",
    criterioDominio: "fechar 3 erros insistentes com regra de prova e mini treino",
    blocoCronometrado: null,
    revisao24hDe: 53,
    revisaoSemanal: false,
    revisaoCumulativa: "puxa apenas erros reincidentes",
    cadernoDeErrosObrigatorio: true,
    prioridadeAprovacao: "alta"
  },
  {
    numero: 55,
    data: "2026-06-05",
    semana: 11,
    fase: "fase-4-dominio-hibrido",
    titulo: "Revisão da Semana 11 + Desafio Misto 11",
    disciplina: "Domínio de Prova",
    disciplinaNome: "Domínio de Prova",
    disciplinaIcone: "⚔️",
    reino: "Reino dos Simulados",
    reinoIcone: "⚔️",
    expansao: "Revisão 24h + checklist do que ainda vacila após dois ciclos de simulado.",
    raridade: "raro",
    xp: 15,
    moedas: 5,
    arquivo: "apostilas/dia-055.html",
    iconeMissao: "🎯",
    funcaoPedagogica: "consolidacao_pos_simulado",
    habilidadePrincipal: "estabilizar desempenho e checklist de risco",
    habilidadeSecundaria: "mapear o que ainda ameaça a prova",
    focoDeProva: "reduzir oscilação, não buscar volume",
    tempoMeta: "60 a 75 min",
    criterioDominio: "75% no bloco curto + checklist preenchido de risco",
    blocoCronometrado: {
      ativo: true,
      duracaoMin: 12,
      objetivo: "checagem de estabilidade"
    },
    revisao24hDe: 54,
    revisaoSemanal: true,
    revisaoCumulativa: "sintetiza Semana 11",
    cadernoDeErrosObrigatorio: true,
    prioridadeAprovacao: "alta"
  },
  {
    numero: 56,
    data: "2026-06-08",
    semana: 12,
    fase: "fase-4-dominio-hibrido",
    titulo: "Prova sob Pressão — Ritmo e Atenção",
    disciplina: "Domínio de Prova",
    disciplinaNome: "Domínio de Prova",
    disciplinaIcone: "⚔️",
    reino: "Reino dos Simulados",
    reinoIcone: "⚔️",
    expansao: "Treino de ritmo com tempo contado e foco sustentado.",
    raridade: "raro",
    xp: 15,
    moedas: 5,
    arquivo: "apostilas/dia-056.html",
    iconeMissao: "⏳",
    funcaoPedagogica: "tempo_e_estrategia",
    habilidadePrincipal: "manter ritmo sem perder precisão",
    habilidadeSecundaria: "monitorar atenção durante bloco sob tempo",
    focoDeProva: "não acelerar demais nas primeiras questões",
    tempoMeta: "60 a 75 min",
    criterioDominio: "aplicar bloco sob tempo com marcação de travamentos",
    blocoCronometrado: {
      ativo: true,
      duracaoMin: 25,
      objetivo: "ritmo e atenção sob pressão"
    },
    revisao24hDe: 55,
    revisaoSemanal: false,
    revisaoCumulativa: "puxa erros persistentes das semanas 10 e 11",
    cadernoDeErrosObrigatorio: true,
    prioridadeAprovacao: "alta"
  },
  {
    numero: 57,
    data: "2026-06-09",
    semana: 12,
    fase: "fase-4-dominio-hibrido",
    titulo: "Correção de Erros Recorrentes",
    disciplina: "Correção Estratégica",
    disciplinaNome: "Correção Estratégica",
    disciplinaIcone: "🧠",
    reino: "Reino dos Simulados",
    reinoIcone: "⚔️",
    expansao: "Mapear padrão de erro e agir com precisão.",
    raridade: "incomum",
    xp: 12,
    moedas: 4,
    arquivo: "apostilas/dia-057.html",
    iconeMissao: "🧠",
    funcaoPedagogica: "correcao_estrategica",
    habilidadePrincipal: "reconhecer padrão de erro recorrente",
    habilidadeSecundaria: "escrever regra pessoal de prevenção",
    focoDeProva: "erro recorrente precisa de protocolo, não de promessa",
    tempoMeta: "60 a 75 min",
    criterioDominio: "todo erro recorrente com protocolo escrito de prevenção",
    blocoCronometrado: null,
    revisao24hDe: 56,
    revisaoSemanal: false,
    revisaoCumulativa: "retoma itens errados do bloco sob pressão",
    cadernoDeErrosObrigatorio: true,
    prioridadeAprovacao: "alta"
  },
  {
    numero: 58,
    data: "2026-06-10",
    semana: 12,
    fase: "fase-4-dominio-hibrido",
    titulo: "Prova sob Pressão — Bloco Final",
    disciplina: "Domínio de Prova",
    disciplinaNome: "Domínio de Prova",
    disciplinaIcone: "⚔️",
    reino: "Reino dos Simulados",
    reinoIcone: "⚔️",
    expansao: "Bloco decisivo em ritmo próximo ao real.",
    raridade: "raro",
    xp: 15,
    moedas: 5,
    arquivo: "apostilas/dia-058.html",
    iconeMissao: "⏳",
    funcaoPedagogica: "tempo_e_estrategia",
    habilidadePrincipal: "aplicar correções dentro de bloco realista",
    habilidadeSecundaria: "testar ordem de ataque e retorno",
    focoDeProva: "não travar no meio do bloco",
    tempoMeta: "60 a 75 min",
    criterioDominio: "melhorar ritmo ou manter acerto com menos travas",
    blocoCronometrado: {
      ativo: true,
      duracaoMin: 30,
      objetivo: "bloco final sob pressão"
    },
    revisao24hDe: 57,
    revisaoSemanal: false,
    revisaoCumulativa: "retoma protocolos de prevenção",
    cadernoDeErrosObrigatorio: true,
    prioridadeAprovacao: "alta"
  },
  {
    numero: 59,
    data: "2026-06-11",
    semana: 12,
    fase: "fase-4-dominio-hibrido",
    titulo: "Treino de Tempo + Marcação Inteligente",
    disciplina: "Domínio de Prova",
    disciplinaNome: "Domínio de Prova",
    disciplinaIcone: "⚔️",
    reino: "Reino dos Simulados",
    reinoIcone: "⚔️",
    expansao: "Saber quando avançar, voltar e revisar.",
    raridade: "incomum",
    xp: 12,
    moedas: 4,
    arquivo: "apostilas/dia-059.html",
    iconeMissao: "⚔️",
    funcaoPedagogica: "tempo_e_estrategia",
    habilidadePrincipal: "decidir quando insistir, pular e revisar",
    habilidadeSecundaria: "criar ordem pessoal de prova",
    focoDeProva: "tempo não é só relógio, é decisão",
    tempoMeta: "60 a 75 min",
    criterioDominio: "protocolo pessoal de tempo escrito e testado",
    blocoCronometrado: {
      ativo: true,
      duracaoMin: 10,
      objetivo: "simulação de pular e voltar"
    },
    revisao24hDe: 58,
    revisaoSemanal: false,
    revisaoCumulativa: "retoma bloco final",
    cadernoDeErrosObrigatorio: true,
    prioridadeAprovacao: "alta"
  },
  {
    numero: 60,
    data: "2026-06-12",
    semana: 12,
    fase: "fase-4-dominio-hibrido",
    titulo: "Revisão da Semana 12 + Desafio Misto 12",
    disciplina: "Domínio de Prova",
    disciplinaNome: "Domínio de Prova",
    disciplinaIcone: "⚔️",
    reino: "Reino dos Simulados",
    reinoIcone: "⚔️",
    expansao: "Consolidação dos protocolos de prova antes da reta final.",
    raridade: "raro",
    xp: 15,
    moedas: 5,
    arquivo: "apostilas/dia-060.html",
    iconeMissao: "🎯",
    funcaoPedagogica: "fechamento_de_protocolo",
    habilidadePrincipal: "consolidar estratégia pessoal de prova",
    habilidadeSecundaria: "detectar último padrão de erro evitável",
    focoDeProva: "chegar à reta final com método, não só conteúdo",
    tempoMeta: "60 a 75 min",
    criterioDominio: "75% no bloco + protocolo final validado",
    blocoCronometrado: {
      ativo: true,
      duracaoMin: 15,
      objetivo: "consolidação do protocolo de prova"
    },
    revisao24hDe: 59,
    revisaoSemanal: true,
    revisaoCumulativa: "sintetiza Semana 12",
    cadernoDeErrosObrigatorio: true,
    prioridadeAprovacao: "alta"
  },
  {
    numero: 61,
    data: "2026-06-15",
    semana: 13,
    fase: "fase-5-sprint-final",
    titulo: "Revisão de Português que Mais Cai",
    disciplina: "Revisão Final",
    disciplinaNome: "Revisão Final",
    disciplinaIcone: "📘",
    reino: "Reino da Coroa",
    reinoIcone: "👑",
    expansao: "Leitura, inferência, efeito de sentido, comando e gramática realmente útil.",
    raridade: "incomum",
    xp: 12,
    moedas: 4,
    arquivo: "apostilas/dia-061.html",
    iconeMissao: "📘",
    funcaoPedagogica: "revisao_cirurgica",
    habilidadePrincipal: "revisar apenas habilidades de Português de maior impacto",
    habilidadeSecundaria: "puxar erros reais do caderno de erros",
    focoDeProva: "não revisar tudo igual; revisar o que mais derruba",
    tempoMeta: "60 a 75 min",
    criterioDominio: "lista curta com 80% + revisão dos erros reais",
    blocoCronometrado: null,
    revisao24hDe: 60,
    revisaoSemanal: false,
    revisaoCumulativa: "puxa top 5 erros de Português",
    cadernoDeErrosObrigatorio: true,
    prioridadeAprovacao: "alta"
  },
  {
    numero: 62,
    data: "2026-06-16",
    semana: 13,
    fase: "fase-5-sprint-final",
    titulo: "Revisão de Matemática que Mais Cai",
    disciplina: "Revisão Final",
    disciplinaNome: "Revisão Final",
    disciplinaIcone: "🧮",
    reino: "Reino da Coroa",
    reinoIcone: "👑",
    expansao: "Operações, frações, decimais, porcentagem, medidas e geometria de maior impacto.",
    raridade: "incomum",
    xp: 12,
    moedas: 4,
    arquivo: "apostilas/dia-062.html",
    iconeMissao: "🧮",
    funcaoPedagogica: "revisao_cirurgica",
    habilidadePrincipal: "revisar apenas habilidades matemáticas de maior impacto",
    habilidadeSecundaria: "puxar erros reais do caderno de erros",
    focoDeProva: "trocar volume por precisão",
    tempoMeta: "60 a 75 min",
    criterioDominio: "lista curta com 80% + reparo dos erros reais",
    blocoCronometrado: null,
    revisao24hDe: 61,
    revisaoSemanal: false,
    revisaoCumulativa: "puxa top 5 erros de Matemática",
    cadernoDeErrosObrigatorio: true,
    prioridadeAprovacao: "alta"
  },
  {
    numero: 63,
    data: "2026-06-17",
    semana: 13,
    fase: "fase-5-sprint-final",
    titulo: "Lista Mista de Alta Prioridade",
    disciplina: "Revisão Final",
    disciplinaNome: "Revisão Final",
    disciplinaIcone: "⚔️",
    reino: "Reino da Coroa",
    reinoIcone: "👑",
    expansao: "Questões escolhidas pelos erros mais comuns do próprio percurso.",
    raridade: "raro",
    xp: 15,
    moedas: 5,
    arquivo: "apostilas/dia-063.html",
    iconeMissao: "⚔️",
    funcaoPedagogica: "revisao_cirurgica",
    habilidadePrincipal: "misturar só o que mais ameaça a aprovação",
    habilidadeSecundaria: "treinar recuperação ativa por erro",
    focoDeProva: "resolver o que é prioritário, não o que é confortável",
    tempoMeta: "60 a 75 min",
    criterioDominio: "75% na lista priorizada + redução do erro recorrente",
    blocoCronometrado: {
      ativo: true,
      duracaoMin: 12,
      objetivo: "lista enxuta de alta prioridade"
    },
    revisao24hDe: 62,
    revisaoSemanal: false,
    revisaoCumulativa: "mistura top erros das duas matérias",
    cadernoDeErrosObrigatorio: true,
    prioridadeAprovacao: "alta"
  },
  {
    numero: 64,
    data: "2026-06-18",
    semana: 13,
    fase: "fase-5-sprint-final",
    titulo: "Correção Comentada dos Erros Mais Frequentes",
    disciplina: "Revisão Final",
    disciplinaNome: "Revisão Final",
    disciplinaIcone: "🧠",
    reino: "Reino da Coroa",
    reinoIcone: "👑",
    expansao: "Consolidar acertos a partir da análise do erro.",
    raridade: "incomum",
    xp: 12,
    moedas: 4,
    arquivo: "apostilas/dia-064.html",
    iconeMissao: "🧠",
    funcaoPedagogica: "recuperacao_de_erros",
    habilidadePrincipal: "fechar erros mais frequentes com regra curta e treino curto",
    habilidadeSecundaria: "reduzir ansiedade por clareza",
    focoDeProva: "erro comentado vale mais do que revisão genérica",
    tempoMeta: "60 a 75 min",
    criterioDominio: "fechar top 5 erros com regra e mini reparo",
    blocoCronometrado: null,
    revisao24hDe: 63,
    revisaoSemanal: false,
    revisaoCumulativa: "puxa a lista de alta prioridade",
    cadernoDeErrosObrigatorio: true,
    prioridadeAprovacao: "alta"
  },
  {
    numero: 65,
    data: "2026-06-19",
    semana: 13,
    fase: "fase-5-sprint-final",
    titulo: "Revisão da Semana 13 + Desafio Misto 13",
    disciplina: "Revisão Final",
    disciplinaNome: "Revisão Final",
    disciplinaIcone: "⚔️",
    reino: "Reino da Coroa",
    reinoIcone: "👑",
    expansao: "Bloco enxuto e decisivo baseado em erro real e conteúdos mais cobrados.",
    raridade: "raro",
    xp: 15,
    moedas: 5,
    arquivo: "apostilas/dia-065.html",
    iconeMissao: "🎯",
    funcaoPedagogica: "checkpoint_cirurgico",
    habilidadePrincipal: "confirmar que os erros mais caros diminuíram",
    habilidadeSecundaria: "decidir foco da última semana",
    focoDeProva: "revisão final precisa ser leve e certeira",
    tempoMeta: "60 a 75 min",
    criterioDominio: "75% no bloco + definição clara do foco da Semana 14",
    blocoCronometrado: {
      ativo: true,
      duracaoMin: 12,
      objetivo: "checkpoint cirúrgico final"
    },
    revisao24hDe: 64,
    revisaoSemanal: true,
    revisaoCumulativa: "sintetiza Semana 13",
    cadernoDeErrosObrigatorio: true,
    prioridadeAprovacao: "alta"
  },
  {
    numero: 66,
    data: "2026-06-22",
    semana: 14,
    fase: "fase-5-sprint-final",
    titulo: "Sprint Final — Leitura e Atenção",
    disciplina: "Sprint Final",
    disciplinaNome: "Sprint Final",
    disciplinaIcone: "📘",
    reino: "Reino da Coroa",
    reinoIcone: "👑",
    expansao: "Comandos, leitura fina, calma e confiança.",
    raridade: "incomum",
    xp: 12,
    moedas: 4,
    arquivo: "apostilas/dia-066.html",
    iconeMissao: "📘",
    funcaoPedagogica: "lapidacao_final",
    habilidadePrincipal: "manter leitura de comando e atenção sem exaustão",
    habilidadeSecundaria: "consolidar confiança com base em evidência",
    focoDeProva: "entrar leve, não sobrecarregado",
    tempoMeta: "45 a 60 min",
    criterioDominio: "bloco curto com 80% e sensação de controle",
    blocoCronometrado: {
      ativo: true,
      duracaoMin: 8,
      objetivo: "leitura fina sem fadiga"
    },
    revisao24hDe: 65,
    revisaoSemanal: false,
    revisaoCumulativa: "puxa últimos erros de leitura",
    cadernoDeErrosObrigatorio: true,
    prioridadeAprovacao: "alta"
  },
  {
    numero: 67,
    data: "2026-06-23",
    semana: 14,
    fase: "fase-5-sprint-final",
    titulo: "Sprint Final — Cálculo e Precisão",
    disciplina: "Sprint Final",
    disciplinaNome: "Sprint Final",
    disciplinaIcone: "🧮",
    reino: "Reino da Coroa",
    reinoIcone: "👑",
    expansao: "Contas essenciais e redução de erros bobos.",
    raridade: "incomum",
    xp: 12,
    moedas: 4,
    arquivo: "apostilas/dia-067.html",
    iconeMissao: "🧮",
    funcaoPedagogica: "lapidacao_final",
    habilidadePrincipal: "manter precisão em contas de maior recorrência",
    habilidadeSecundaria: "reduzir erro bobo por pressa",
    focoDeProva: "não inventar novidade perto da prova",
    tempoMeta: "45 a 60 min",
    criterioDominio: "bloco curto com 80% e sem erro evitável grave",
    blocoCronometrado: {
      ativo: true,
      duracaoMin: 8,
      objetivo: "cálculo preciso e leve"
    },
    revisao24hDe: 66,
    revisaoSemanal: false,
    revisaoCumulativa: "puxa últimos erros de matemática",
    cadernoDeErrosObrigatorio: true,
    prioridadeAprovacao: "alta"
  },
  {
    numero: 68,
    data: "2026-06-24",
    semana: 14,
    fase: "fase-5-sprint-final",
    titulo: "Sprint Final — Simulado Curto",
    disciplina: "Sprint Final",
    disciplinaNome: "Sprint Final",
    disciplinaIcone: "🏆",
    reino: "Reino da Coroa",
    reinoIcone: "👑",
    expansao: "Simulado curto para manter o motor ligado sem cansar demais.",
    raridade: "raro",
    xp: 15,
    moedas: 5,
    arquivo: "apostilas/dia-068.html",
    iconeMissao: "🏆",
    funcaoPedagogica: "lapidacao_final",
    habilidadePrincipal: "testar prontidão sem esgotar energia",
    habilidadeSecundaria: "reafirmar protocolo de prova",
    focoDeProva: "manter ritmo e confiança, não buscar volume",
    tempoMeta: "45 a 60 min",
    criterioDominio: "aplicar simulado curto e revisar só erros evitáveis",
    blocoCronometrado: {
      ativo: true,
      duracaoMin: 20,
      objetivo: "simulado curto de manutenção"
    },
    revisao24hDe: 67,
    revisaoSemanal: false,
    revisaoCumulativa: "mistura últimos pontos sensíveis",
    cadernoDeErrosObrigatorio: true,
    prioridadeAprovacao: "alta"
  },
  {
    numero: 69,
    data: "2026-06-25",
    semana: 14,
    fase: "fase-5-sprint-final",
    titulo: "Sprint Final — Correção e Confiança",
    disciplina: "Sprint Final",
    disciplinaNome: "Sprint Final",
    disciplinaIcone: "🧠",
    reino: "Reino da Coroa",
    reinoIcone: "👑",
    expansao: "Últimos ajustes com serenidade e clareza.",
    raridade: "incomum",
    xp: 12,
    moedas: 4,
    arquivo: "apostilas/dia-069.html",
    iconeMissao: "🧠",
    funcaoPedagogica: "lapidacao_final",
    habilidadePrincipal: "corrigir apenas o que ainda é evitável",
    habilidadeSecundaria: "elevar confiança por evidência e não por fala motivacional",
    focoDeProva: "fechar a preparação sem abrir novos buracos",
    tempoMeta: "40 a 55 min",
    criterioDominio: "errar pouco e saber exatamente o que revisar de forma leve",
    blocoCronometrado: null,
    revisao24hDe: 68,
    revisaoSemanal: false,
    revisaoCumulativa: "retoma apenas erros do simulado curto",
    cadernoDeErrosObrigatorio: true,
    prioridadeAprovacao: "alta"
  },
  {
    numero: 70,
    data: "2026-06-26",
    semana: 14,
    fase: "fase-5-sprint-final",
    titulo: "Véspera Inteligente + Revisão Final",
    disciplina: "Sprint Final",
    disciplinaNome: "Sprint Final",
    disciplinaIcone: "👑",
    reino: "Reino da Coroa",
    reinoIcone: "👑",
    expansao: "Revisão leve, confiança alta e preparação mental.",
    raridade: "raro",
    xp: 15,
    moedas: 5,
    arquivo: "apostilas/dia-070.html",
    iconeMissao: "👑",
    funcaoPedagogica: "vespera_inteligente",
    habilidadePrincipal: "chegar descansado, atento e seguro",
    habilidadeSecundaria: "relembrar protocolo mental e itens essenciais",
    focoDeProva: "não cansar na véspera",
    tempoMeta: "30 a 45 min",
    criterioDominio: "revisão leve, zero sobrecarga e protocolo final revisado",
    blocoCronometrado: null,
    revisao24hDe: 69,
    revisaoSemanal: true,
    revisaoCumulativa: "síntese final do essencial",
    cadernoDeErrosObrigatorio: true,
    prioridadeAprovacao: "alta"
  }
];

window.CONFIG = { projeto, fases, semanas, dias };

window.getDiaPorData = function(dateISO) {
  return (window.CONFIG.dias || []).find(d => d.data === dateISO) || null;
};

window.getRecompensaDaSemana = function(semana) {
  const week = (window.CONFIG.semanas || []).find(w => w.semana === semana);
  return week ? week.recompensaSemana : null;
};
