/* EIJI — configuração pedagógica v4\n   Base corrigida para calendário real: domingos entram na numeração como folga. */\n\nconst projeto = {
  "slug": "desafio-objetivo-eiji-calendario-real",
  "titulo": "Jornada do Eiji — Calendário Real",
  "subtitulo": "97 dias de calendário, 84 encontros de estudo e folga todo domingo.",
  "aluno": "Eiji",
  "totalDias": 97,
  "totalEncontros": 84,
  "totalFolgas": 13,
  "totalSemanas": 14,
  "dataInicio": "2026-03-23",
  "dataFim": "2026-06-27",
  "duracaoDiaria": "20 a 90 minutos",
  "foco": "Português e Matemática",
  "versaoCronograma": "v4_calendario_real_com_domingos",
  "regraCentral": "a numeração segue os dias corridos do calendário; domingos existem na contagem, mas são folga"
};

const fases = [
  {
    "id": "fase-1-base-5ano",
    "icone": "📚",
    "titulo": "Fase 1 — Base de Aprovação",
    "inicioSemana": 1,
    "fimSemana": 3
  },
  {
    "id": "fase-2-consolidacao-aceleracao",
    "icone": "🧮",
    "titulo": "Fase 2 — Consolidação com Aceleração",
    "inicioSemana": 4,
    "fimSemana": 6
  },
  {
    "id": "fase-3-ponte-6ano",
    "icone": "🏹",
    "titulo": "Fase 3 — Ponte de Complexidade",
    "inicioSemana": 7,
    "fimSemana": 9
  },
  {
    "id": "fase-4-dominio-hibrido",
    "icone": "⚔️",
    "titulo": "Fase 4 — Domínio de Prova",
    "inicioSemana": 10,
    "fimSemana": 12
  },
  {
    "id": "fase-5-sprint-final",
    "icone": "👑",
    "titulo": "Fase 5 — Sprint Final",
    "inicioSemana": 13,
    "fimSemana": 14
  }
];

const semanas = [
  {
    "semana": 1,
    "fase": "fase-1-base-5ano",
    "titulo": "Base e diagnóstico inicial",
    "descricao": "Ideia principal, fato x opinião, explícito e implícito, operações básicas e primeiro simuladinho no sábado.",
    "objetivoAprovacao": "fechar buracos cedo e iniciar treino de prova semanal"
  },
  {
    "semana": 2,
    "fase": "fase-1-base-5ano",
    "titulo": "Automatização inicial",
    "descricao": "Inferência, vocabulário em contexto, comando da questão, sequência lógica e segundo simuladinho no sábado.",
    "objetivoAprovacao": "reduzir erro de comando e ganhar ritmo semanal de prova"
  },
  {
    "semana": 3,
    "fase": "fase-1-base-5ano",
    "titulo": "Primeira consolidação forte",
    "descricao": "Pontuação, classes de palavras, referência pronominal, ortografia e frações, com checkpoint e simuladinho no sábado.",
    "objetivoAprovacao": "consolidar a base e validar aprendizagem com simulado semanal"
  },
  {
    "semana": 4,
    "fase": "fase-2-consolidacao-aceleracao",
    "titulo": "Leitura funcional e decimais",
    "descricao": "Gêneros textuais, finalidade, enunciado útil, decimais e medidas, com simuladinho funcional no sábado.",
    "objetivoAprovacao": "ligar leitura útil a matemática prática e hábito de prova"
  },
  {
    "semana": 5,
    "fase": "fase-2-consolidacao-aceleracao",
    "titulo": "Cotidiano de prova",
    "descricao": "Coesão, pronomes, porcentagem, dinheiro, gráficos e tirinhas, com simuladinho contextual no sábado.",
    "objetivoAprovacao": "aproximar o treino do estilo mais frequente do vestibulinho"
  },
  {
    "semana": 6,
    "fase": "fase-2-consolidacao-aceleracao",
    "titulo": "Forma, espaço e pegadinha",
    "descricao": "Humor, ironia, reescrita, perímetro, área e geometria, com simuladinho de alternativas próximas no sábado.",
    "objetivoAprovacao": "começar a treinar pegadinhas reais toda semana"
  },
  {
    "semana": 7,
    "fase": "fase-3-ponte-6ano",
    "titulo": "Cruzamento de informações",
    "descricao": "Comparação entre textos, opinião x fato, operações combinadas e problemas longos, com simuladinho de resistência no sábado.",
    "objetivoAprovacao": "ganhar resistência cognitiva sem perder clareza"
  },
  {
    "semana": 8,
    "fase": "fase-3-ponte-6ano",
    "titulo": "Coerência e alternativas",
    "descricao": "Reescrita, coerência, razão, média e tabelas, com simuladinho de eliminação de alternativas no sábado.",
    "objetivoAprovacao": "aprender a decidir melhor entre opções parecidas"
  },
  {
    "semana": 9,
    "fase": "fase-3-ponte-6ano",
    "titulo": "Pegadinhas reais",
    "descricao": "Efeito de sentido, verbal e não verbal, medidas, conversões e geometria aplicada, com simuladinho sob pressão no sábado.",
    "objetivoAprovacao": "diminuir erro por desatenção e consolidar matemática aplicada"
  },
  {
    "semana": 10,
    "fase": "fase-4-dominio-hibrido",
    "titulo": "Mini simulado 1",
    "descricao": "Primeiro ciclo formal de simulado, correção guiada, reensino e sábado de consolidação sob tempo.",
    "objetivoAprovacao": "medir desempenho real e abrir recuperação cirúrgica"
  },
  {
    "semana": 11,
    "fase": "fase-4-dominio-hibrido",
    "titulo": "Mini simulado 2",
    "descricao": "Novo ciclo de simulado com foco em consistência, correção e sábado de estabilização.",
    "objetivoAprovacao": "reduzir oscilação e consolidar comportamento de prova"
  },
  {
    "semana": 12,
    "fase": "fase-4-dominio-hibrido",
    "titulo": "Tempo e estratégia",
    "descricao": "Treino sob pressão com gestão de tempo, marcação inteligente e sábado de prova curta controlada.",
    "objetivoAprovacao": "criar protocolo mental para não travar na prova"
  },
  {
    "semana": 13,
    "fase": "fase-5-sprint-final",
    "titulo": "Revisão baseada em erro",
    "descricao": "Português e Matemática mais cobrados, puxados pelo histórico de erros, com simuladinho cirúrgico no sábado.",
    "objetivoAprovacao": "trocar revisão genérica por revisão de alto impacto"
  },
  {
    "semana": 14,
    "fase": "fase-5-sprint-final",
    "titulo": "Lapidação final",
    "descricao": "Sprint final com revisão leve, simulado curto no sábado e véspera inteligente.",
    "objetivoAprovacao": "chegar inteiro, atento e confiante para o dia decisivo"
  }
];

const dias = [
  {
    "numero": 1,
    "data": "2026-03-23",
    "diaSemana": "segunda-feira",
    "semana": 1,
    "titulo": "Ideia Principal do Texto",
    "disciplinaNome": "Português + Matemática",
    "arquivo": "apostilas/dia-001.html",
    "funcaoPedagogica": "conteudo_novo",
    "tempoMeta": "60 a 90 min",
    "observacao": "Base e diagnóstico inicial",
    "prioridadeAprovacao": "média"
  },
  {
    "numero": 2,
    "data": "2026-03-24",
    "diaSemana": "terça-feira",
    "semana": 1,
    "titulo": "Fatos, Opiniões e Adição/Subtração",
    "disciplinaNome": "Português + Matemática",
    "arquivo": "apostilas/dia-002.html",
    "funcaoPedagogica": "conteudo_novo_com_revisao_24h",
    "tempoMeta": "60 a 90 min",
    "observacao": "Base e diagnóstico inicial",
    "prioridadeAprovacao": "média"
  },
  {
    "numero": 3,
    "data": "2026-03-25",
    "diaSemana": "quarta-feira",
    "semana": 1,
    "titulo": "Informação Explícita e Implícita",
    "disciplinaNome": "Português + Matemática",
    "arquivo": "apostilas/dia-003.html",
    "funcaoPedagogica": "conteudo_novo_com_revisao_24h",
    "tempoMeta": "60 a 90 min",
    "observacao": "Base e diagnóstico inicial",
    "prioridadeAprovacao": "média"
  },
  {
    "numero": 4,
    "data": "2026-03-26",
    "diaSemana": "quinta-feira",
    "semana": 1,
    "titulo": "Adição, Subtração e Problemas do Cotidiano",
    "disciplinaNome": "Português + Matemática",
    "arquivo": "apostilas/dia-004.html",
    "funcaoPedagogica": "conteudo_aplicado",
    "tempoMeta": "60 a 90 min",
    "observacao": "Base e diagnóstico inicial",
    "prioridadeAprovacao": "média"
  },
  {
    "numero": 5,
    "data": "2026-03-27",
    "diaSemana": "sexta-feira",
    "semana": 1,
    "titulo": "Revisão da Semana 1 + Caderno de Erros",
    "disciplinaNome": "Português + Matemática",
    "arquivo": "apostilas/dia-005.html",
    "funcaoPedagogica": "checkpoint_semanal",
    "tempoMeta": "60 a 90 min",
    "observacao": "Base e diagnóstico inicial",
    "prioridadeAprovacao": "média"
  },
  {
    "numero": 6,
    "data": "2026-03-28",
    "diaSemana": "sábado",
    "semana": 1,
    "titulo": "Simuladinho 1 — Base Inicial",
    "disciplinaNome": "Simulado Semanal",
    "arquivo": "apostilas/dia-006.html",
    "funcaoPedagogica": "simulado_semanal",
    "tempoMeta": "20 a 25 min",
    "observacao": "Base e diagnóstico inicial",
    "prioridadeAprovacao": "média"
  },
  {
    "numero": 7,
    "data": "2026-03-29",
    "diaSemana": "domingo",
    "semana": 1,
    "titulo": "Folga / Recuperação Leve",
    "disciplinaNome": "Descanso",
    "arquivo": null,
    "funcaoPedagogica": "folga",
    "tempoMeta": "Folga",
    "observacao": "Domingo sem apostila. Descanso, leitura leve ou recuperação opcional do caderno de erros.",
    "prioridadeAprovacao": "média"
  },
  {
    "numero": 8,
    "data": "2026-03-30",
    "diaSemana": "segunda-feira",
    "semana": 2,
    "titulo": "Inferência Inicial + Cálculo Mental",
    "disciplinaNome": "Português + Matemática",
    "arquivo": "apostilas/dia-008.html",
    "funcaoPedagogica": "conteudo_novo",
    "tempoMeta": "60 a 90 min",
    "observacao": "Automatização inicial",
    "prioridadeAprovacao": "média"
  },
  {
    "numero": 9,
    "data": "2026-03-31",
    "diaSemana": "terça-feira",
    "semana": 2,
    "titulo": "Sinônimos, Antônimos e Tabuada Estratégica",
    "disciplinaNome": "Português + Matemática",
    "arquivo": "apostilas/dia-009.html",
    "funcaoPedagogica": "conteudo_novo_com_revisao_24h",
    "tempoMeta": "60 a 90 min",
    "observacao": "Automatização inicial",
    "prioridadeAprovacao": "média"
  },
  {
    "numero": 10,
    "data": "2026-04-01",
    "diaSemana": "quarta-feira",
    "semana": 2,
    "titulo": "Comando da Questão + Multiplicação",
    "disciplinaNome": "Português + Matemática",
    "arquivo": "apostilas/dia-010.html",
    "funcaoPedagogica": "conteudo_novo_com_revisao_24h",
    "tempoMeta": "60 a 90 min",
    "observacao": "Automatização inicial",
    "prioridadeAprovacao": "média"
  },
  {
    "numero": 11,
    "data": "2026-04-02",
    "diaSemana": "quinta-feira",
    "semana": 2,
    "titulo": "Sequência Lógica + Divisão",
    "disciplinaNome": "Português + Matemática",
    "arquivo": "apostilas/dia-011.html",
    "funcaoPedagogica": "conteudo_aplicado",
    "tempoMeta": "60 a 90 min",
    "observacao": "Automatização inicial",
    "prioridadeAprovacao": "média"
  },
  {
    "numero": 12,
    "data": "2026-04-03",
    "diaSemana": "sexta-feira",
    "semana": 2,
    "titulo": "Revisão da Semana 2 + Caderno de Erros",
    "disciplinaNome": "Português + Matemática",
    "arquivo": "apostilas/dia-012.html",
    "funcaoPedagogica": "checkpoint_semanal",
    "tempoMeta": "60 a 90 min",
    "observacao": "Automatização inicial",
    "prioridadeAprovacao": "média"
  },
  {
    "numero": 13,
    "data": "2026-04-04",
    "diaSemana": "sábado",
    "semana": 2,
    "titulo": "Simuladinho 2 — Comando e Inferência",
    "disciplinaNome": "Simulado Semanal",
    "arquivo": "apostilas/dia-013.html",
    "funcaoPedagogica": "simulado_semanal",
    "tempoMeta": "20 a 25 min",
    "observacao": "Automatização inicial",
    "prioridadeAprovacao": "média"
  },
  {
    "numero": 14,
    "data": "2026-04-05",
    "diaSemana": "domingo",
    "semana": 2,
    "titulo": "Folga / Recuperação Leve",
    "disciplinaNome": "Descanso",
    "arquivo": null,
    "funcaoPedagogica": "folga",
    "tempoMeta": "Folga",
    "observacao": "Domingo sem apostila. Descanso, leitura leve ou recuperação opcional do caderno de erros.",
    "prioridadeAprovacao": "média"
  },
  {
    "numero": 15,
    "data": "2026-04-06",
    "diaSemana": "segunda-feira",
    "semana": 3,
    "titulo": "Pontuação que Muda Sentido + Frações Básicas",
    "disciplinaNome": "Português + Matemática",
    "arquivo": "apostilas/dia-015.html",
    "funcaoPedagogica": "conteudo_novo",
    "tempoMeta": "60 a 90 min",
    "observacao": "Primeira consolidação forte",
    "prioridadeAprovacao": "alta"
  },
  {
    "numero": 16,
    "data": "2026-04-07",
    "diaSemana": "terça-feira",
    "semana": 3,
    "titulo": "Classes de Palavras + Frações na Prática",
    "disciplinaNome": "Português + Matemática",
    "arquivo": "apostilas/dia-016.html",
    "funcaoPedagogica": "conteudo_novo_com_revisao_24h",
    "tempoMeta": "60 a 90 min",
    "observacao": "Primeira consolidação forte",
    "prioridadeAprovacao": "alta"
  },
  {
    "numero": 17,
    "data": "2026-04-08",
    "diaSemana": "quarta-feira",
    "semana": 3,
    "titulo": "Referência Pronominal + Frações Equivalentes",
    "disciplinaNome": "Português + Matemática",
    "arquivo": "apostilas/dia-017.html",
    "funcaoPedagogica": "conteudo_novo_com_revisao_24h",
    "tempoMeta": "60 a 90 min",
    "observacao": "Primeira consolidação forte",
    "prioridadeAprovacao": "alta"
  },
  {
    "numero": 18,
    "data": "2026-04-09",
    "diaSemana": "quinta-feira",
    "semana": 3,
    "titulo": "Ortografia Frequente + Comparação de Frações",
    "disciplinaNome": "Português + Matemática",
    "arquivo": "apostilas/dia-018.html",
    "funcaoPedagogica": "conteudo_aplicado",
    "tempoMeta": "60 a 90 min",
    "observacao": "Primeira consolidação forte",
    "prioridadeAprovacao": "alta"
  },
  {
    "numero": 19,
    "data": "2026-04-10",
    "diaSemana": "sexta-feira",
    "semana": 3,
    "titulo": "Revisão da Semana 3 + Checkpoint da Base",
    "disciplinaNome": "Português + Matemática",
    "arquivo": "apostilas/dia-019.html",
    "funcaoPedagogica": "checkpoint_semanal",
    "tempoMeta": "60 a 90 min",
    "observacao": "Primeira consolidação forte",
    "prioridadeAprovacao": "alta"
  },
  {
    "numero": 20,
    "data": "2026-04-11",
    "diaSemana": "sábado",
    "semana": 3,
    "titulo": "Simuladinho 3 — Consolidação da Base",
    "disciplinaNome": "Simulado Semanal",
    "arquivo": "apostilas/dia-020.html",
    "funcaoPedagogica": "simulado_semanal",
    "tempoMeta": "20 a 25 min",
    "observacao": "Primeira consolidação forte",
    "prioridadeAprovacao": "alta"
  },
  {
    "numero": 21,
    "data": "2026-04-12",
    "diaSemana": "domingo",
    "semana": 3,
    "titulo": "Folga / Recuperação Leve",
    "disciplinaNome": "Descanso",
    "arquivo": null,
    "funcaoPedagogica": "folga",
    "tempoMeta": "Folga",
    "observacao": "Domingo sem apostila. Descanso, leitura leve ou recuperação opcional do caderno de erros.",
    "prioridadeAprovacao": "alta"
  },
  {
    "numero": 22,
    "data": "2026-04-13",
    "diaSemana": "segunda-feira",
    "semana": 4,
    "titulo": "Gêneros Textuais + Números Decimais",
    "disciplinaNome": "Português + Matemática",
    "arquivo": "apostilas/dia-022.html",
    "funcaoPedagogica": "conteudo_novo",
    "tempoMeta": "60 a 90 min",
    "observacao": "Leitura funcional e decimais",
    "prioridadeAprovacao": "alta"
  },
  {
    "numero": 23,
    "data": "2026-04-14",
    "diaSemana": "terça-feira",
    "semana": 4,
    "titulo": "Finalidade do Texto + Adição com Decimais",
    "disciplinaNome": "Português + Matemática",
    "arquivo": "apostilas/dia-023.html",
    "funcaoPedagogica": "conteudo_novo_com_revisao_24h",
    "tempoMeta": "60 a 90 min",
    "observacao": "Leitura funcional e decimais",
    "prioridadeAprovacao": "alta"
  },
  {
    "numero": 24,
    "data": "2026-04-15",
    "diaSemana": "quarta-feira",
    "semana": 4,
    "titulo": "Leitura de Enunciado + Subtração com Decimais",
    "disciplinaNome": "Português + Matemática",
    "arquivo": "apostilas/dia-024.html",
    "funcaoPedagogica": "conteudo_novo_com_revisao_24h",
    "tempoMeta": "60 a 90 min",
    "observacao": "Leitura funcional e decimais",
    "prioridadeAprovacao": "alta"
  },
  {
    "numero": 25,
    "data": "2026-04-16",
    "diaSemana": "quinta-feira",
    "semana": 4,
    "titulo": "Resolução Guiada + Medidas de Comprimento",
    "disciplinaNome": "Português + Matemática",
    "arquivo": "apostilas/dia-025.html",
    "funcaoPedagogica": "conteudo_aplicado",
    "tempoMeta": "60 a 90 min",
    "observacao": "Leitura funcional e decimais",
    "prioridadeAprovacao": "alta"
  },
  {
    "numero": 26,
    "data": "2026-04-17",
    "diaSemana": "sexta-feira",
    "semana": 4,
    "titulo": "Revisão da Semana 4 + Desafio Funcional",
    "disciplinaNome": "Português + Matemática",
    "arquivo": "apostilas/dia-026.html",
    "funcaoPedagogica": "checkpoint_semanal",
    "tempoMeta": "60 a 90 min",
    "observacao": "Leitura funcional e decimais",
    "prioridadeAprovacao": "alta"
  },
  {
    "numero": 27,
    "data": "2026-04-18",
    "diaSemana": "sábado",
    "semana": 4,
    "titulo": "Simuladinho 4 — Leitura Funcional",
    "disciplinaNome": "Simulado Semanal",
    "arquivo": "apostilas/dia-027.html",
    "funcaoPedagogica": "simulado_semanal",
    "tempoMeta": "25 a 30 min",
    "observacao": "Leitura funcional e decimais",
    "prioridadeAprovacao": "alta"
  },
  {
    "numero": 28,
    "data": "2026-04-19",
    "diaSemana": "domingo",
    "semana": 4,
    "titulo": "Folga / Recuperação Leve",
    "disciplinaNome": "Descanso",
    "arquivo": null,
    "funcaoPedagogica": "folga",
    "tempoMeta": "Folga",
    "observacao": "Domingo sem apostila. Descanso, leitura leve ou recuperação opcional do caderno de erros.",
    "prioridadeAprovacao": "alta"
  },
  {
    "numero": 29,
    "data": "2026-04-20",
    "diaSemana": "segunda-feira",
    "semana": 5,
    "titulo": "Coesão Textual + Sistema Monetário",
    "disciplinaNome": "Português + Matemática",
    "arquivo": "apostilas/dia-029.html",
    "funcaoPedagogica": "conteudo_novo",
    "tempoMeta": "60 a 90 min",
    "observacao": "Cotidiano de prova",
    "prioridadeAprovacao": "alta"
  },
  {
    "numero": 30,
    "data": "2026-04-21",
    "diaSemana": "terça-feira",
    "semana": 5,
    "titulo": "Pronomes em Contexto + Porcentagem Básica",
    "disciplinaNome": "Português + Matemática",
    "arquivo": "apostilas/dia-030.html",
    "funcaoPedagogica": "conteudo_novo_com_revisao_24h",
    "tempoMeta": "60 a 90 min",
    "observacao": "Cotidiano de prova",
    "prioridadeAprovacao": "alta"
  },
  {
    "numero": 31,
    "data": "2026-04-22",
    "diaSemana": "quarta-feira",
    "semana": 5,
    "titulo": "Ortografia Atenta + Descontos e Acréscimos",
    "disciplinaNome": "Português + Matemática",
    "arquivo": "apostilas/dia-031.html",
    "funcaoPedagogica": "conteudo_novo_com_revisao_24h",
    "tempoMeta": "60 a 90 min",
    "observacao": "Cotidiano de prova",
    "prioridadeAprovacao": "alta"
  },
  {
    "numero": 32,
    "data": "2026-04-23",
    "diaSemana": "quinta-feira",
    "semana": 5,
    "titulo": "Interpretação de Tiras + Gráficos e Tabelas",
    "disciplinaNome": "Português + Matemática",
    "arquivo": "apostilas/dia-032.html",
    "funcaoPedagogica": "conteudo_aplicado",
    "tempoMeta": "60 a 90 min",
    "observacao": "Cotidiano de prova",
    "prioridadeAprovacao": "alta"
  },
  {
    "numero": 33,
    "data": "2026-04-24",
    "diaSemana": "sexta-feira",
    "semana": 5,
    "titulo": "Revisão da Semana 5 + Contexto de Prova",
    "disciplinaNome": "Português + Matemática",
    "arquivo": "apostilas/dia-033.html",
    "funcaoPedagogica": "checkpoint_semanal",
    "tempoMeta": "60 a 90 min",
    "observacao": "Cotidiano de prova",
    "prioridadeAprovacao": "alta"
  },
  {
    "numero": 34,
    "data": "2026-04-25",
    "diaSemana": "sábado",
    "semana": 5,
    "titulo": "Simuladinho 5 — Contexto Real",
    "disciplinaNome": "Simulado Semanal",
    "arquivo": "apostilas/dia-034.html",
    "funcaoPedagogica": "simulado_semanal",
    "tempoMeta": "25 a 30 min",
    "observacao": "Cotidiano de prova",
    "prioridadeAprovacao": "alta"
  },
  {
    "numero": 35,
    "data": "2026-04-26",
    "diaSemana": "domingo",
    "semana": 5,
    "titulo": "Folga / Recuperação Leve",
    "disciplinaNome": "Descanso",
    "arquivo": null,
    "funcaoPedagogica": "folga",
    "tempoMeta": "Folga",
    "observacao": "Domingo sem apostila. Descanso, leitura leve ou recuperação opcional do caderno de erros.",
    "prioridadeAprovacao": "alta"
  },
  {
    "numero": 36,
    "data": "2026-04-27",
    "diaSemana": "segunda-feira",
    "semana": 6,
    "titulo": "Humor, Ironia e Intenção + Perímetro",
    "disciplinaNome": "Português + Matemática",
    "arquivo": "apostilas/dia-036.html",
    "funcaoPedagogica": "conteudo_novo",
    "tempoMeta": "60 a 90 min",
    "observacao": "Forma, espaço e pegadinha",
    "prioridadeAprovacao": "alta"
  },
  {
    "numero": 37,
    "data": "2026-04-28",
    "diaSemana": "terça-feira",
    "semana": 6,
    "titulo": "Vocabulário no Contexto + Área de Figuras",
    "disciplinaNome": "Português + Matemática",
    "arquivo": "apostilas/dia-037.html",
    "funcaoPedagogica": "conteudo_novo_com_revisao_24h",
    "tempoMeta": "60 a 90 min",
    "observacao": "Forma, espaço e pegadinha",
    "prioridadeAprovacao": "alta"
  },
  {
    "numero": 38,
    "data": "2026-04-29",
    "diaSemana": "quarta-feira",
    "semana": 6,
    "titulo": "Reescrita com Sentido + Geometria Plana",
    "disciplinaNome": "Português + Matemática",
    "arquivo": "apostilas/dia-038.html",
    "funcaoPedagogica": "conteudo_novo_com_revisao_24h",
    "tempoMeta": "60 a 90 min",
    "observacao": "Forma, espaço e pegadinha",
    "prioridadeAprovacao": "alta"
  },
  {
    "numero": 39,
    "data": "2026-04-30",
    "diaSemana": "quinta-feira",
    "semana": 6,
    "titulo": "Problemas em Dois Passos + Sólidos Geométricos",
    "disciplinaNome": "Português + Matemática",
    "arquivo": "apostilas/dia-039.html",
    "funcaoPedagogica": "conteudo_aplicado",
    "tempoMeta": "60 a 90 min",
    "observacao": "Forma, espaço e pegadinha",
    "prioridadeAprovacao": "alta"
  },
  {
    "numero": 40,
    "data": "2026-05-01",
    "diaSemana": "sexta-feira",
    "semana": 6,
    "titulo": "Revisão da Semana 6 + Pegadinhas",
    "disciplinaNome": "Português + Matemática",
    "arquivo": "apostilas/dia-040.html",
    "funcaoPedagogica": "checkpoint_semanal",
    "tempoMeta": "60 a 90 min",
    "observacao": "Forma, espaço e pegadinha",
    "prioridadeAprovacao": "alta"
  },
  {
    "numero": 41,
    "data": "2026-05-02",
    "diaSemana": "sábado",
    "semana": 6,
    "titulo": "Simuladinho 6 — Alternativas Próximas",
    "disciplinaNome": "Simulado Semanal",
    "arquivo": "apostilas/dia-041.html",
    "funcaoPedagogica": "simulado_semanal",
    "tempoMeta": "25 a 30 min",
    "observacao": "Forma, espaço e pegadinha",
    "prioridadeAprovacao": "alta"
  },
  {
    "numero": 42,
    "data": "2026-05-03",
    "diaSemana": "domingo",
    "semana": 6,
    "titulo": "Folga / Recuperação Leve",
    "disciplinaNome": "Descanso",
    "arquivo": null,
    "funcaoPedagogica": "folga",
    "tempoMeta": "Folga",
    "observacao": "Domingo sem apostila. Descanso, leitura leve ou recuperação opcional do caderno de erros.",
    "prioridadeAprovacao": "alta"
  },
  {
    "numero": 43,
    "data": "2026-05-04",
    "diaSemana": "segunda-feira",
    "semana": 7,
    "titulo": "Comparação entre Textos + Operações Combinadas",
    "disciplinaNome": "Português + Matemática",
    "arquivo": "apostilas/dia-043.html",
    "funcaoPedagogica": "conteudo_novo",
    "tempoMeta": "60 a 90 min",
    "observacao": "Cruzamento de informações",
    "prioridadeAprovacao": "alta"
  },
  {
    "numero": 44,
    "data": "2026-05-05",
    "diaSemana": "terça-feira",
    "semana": 7,
    "titulo": "Tese, Opinião e Fato + Problemas Longos",
    "disciplinaNome": "Português + Matemática",
    "arquivo": "apostilas/dia-044.html",
    "funcaoPedagogica": "conteudo_novo_com_revisao_24h",
    "tempoMeta": "60 a 90 min",
    "observacao": "Cruzamento de informações",
    "prioridadeAprovacao": "alta"
  },
  {
    "numero": 45,
    "data": "2026-05-06",
    "diaSemana": "quarta-feira",
    "semana": 7,
    "titulo": "Informações Cruzadas + Decimais em Problemas",
    "disciplinaNome": "Português + Matemática",
    "arquivo": "apostilas/dia-045.html",
    "funcaoPedagogica": "conteudo_novo_com_revisao_24h",
    "tempoMeta": "60 a 90 min",
    "observacao": "Cruzamento de informações",
    "prioridadeAprovacao": "alta"
  },
  {
    "numero": 46,
    "data": "2026-05-07",
    "diaSemana": "quinta-feira",
    "semana": 7,
    "titulo": "Dicas do Enunciado + Frações e Decimais",
    "disciplinaNome": "Português + Matemática",
    "arquivo": "apostilas/dia-046.html",
    "funcaoPedagogica": "conteudo_aplicado",
    "tempoMeta": "60 a 90 min",
    "observacao": "Cruzamento de informações",
    "prioridadeAprovacao": "alta"
  },
  {
    "numero": 47,
    "data": "2026-05-08",
    "diaSemana": "sexta-feira",
    "semana": 7,
    "titulo": "Revisão da Semana 7 + Resistência",
    "disciplinaNome": "Português + Matemática",
    "arquivo": "apostilas/dia-047.html",
    "funcaoPedagogica": "checkpoint_semanal",
    "tempoMeta": "60 a 90 min",
    "observacao": "Cruzamento de informações",
    "prioridadeAprovacao": "alta"
  },
  {
    "numero": 48,
    "data": "2026-05-09",
    "diaSemana": "sábado",
    "semana": 7,
    "titulo": "Simuladinho 7 — Resistência Cognitiva",
    "disciplinaNome": "Simulado Semanal",
    "arquivo": "apostilas/dia-048.html",
    "funcaoPedagogica": "simulado_semanal",
    "tempoMeta": "35 a 40 min",
    "observacao": "Cruzamento de informações",
    "prioridadeAprovacao": "alta"
  },
  {
    "numero": 49,
    "data": "2026-05-10",
    "diaSemana": "domingo",
    "semana": 7,
    "titulo": "Folga / Recuperação Leve",
    "disciplinaNome": "Descanso",
    "arquivo": null,
    "funcaoPedagogica": "folga",
    "tempoMeta": "Folga",
    "observacao": "Domingo sem apostila. Descanso, leitura leve ou recuperação opcional do caderno de erros.",
    "prioridadeAprovacao": "alta"
  },
  {
    "numero": 50,
    "data": "2026-05-11",
    "diaSemana": "segunda-feira",
    "semana": 8,
    "titulo": "Reescrita Inteligente + Razão Simples",
    "disciplinaNome": "Português + Matemática",
    "arquivo": "apostilas/dia-050.html",
    "funcaoPedagogica": "conteudo_novo",
    "tempoMeta": "60 a 90 min",
    "observacao": "Coerência e alternativas",
    "prioridadeAprovacao": "alta"
  },
  {
    "numero": 51,
    "data": "2026-05-12",
    "diaSemana": "terça-feira",
    "semana": 8,
    "titulo": "Coerência e Contradição + Escalas e Proporção",
    "disciplinaNome": "Português + Matemática",
    "arquivo": "apostilas/dia-051.html",
    "funcaoPedagogica": "conteudo_novo_com_revisao_24h",
    "tempoMeta": "60 a 90 min",
    "observacao": "Coerência e alternativas",
    "prioridadeAprovacao": "alta"
  },
  {
    "numero": 52,
    "data": "2026-05-13",
    "diaSemana": "quarta-feira",
    "semana": 8,
    "titulo": "Leitura de Dados + Média Inicial",
    "disciplinaNome": "Português + Matemática",
    "arquivo": "apostilas/dia-052.html",
    "funcaoPedagogica": "conteudo_novo_com_revisao_24h",
    "tempoMeta": "60 a 90 min",
    "observacao": "Coerência e alternativas",
    "prioridadeAprovacao": "alta"
  },
  {
    "numero": 53,
    "data": "2026-05-14",
    "diaSemana": "quinta-feira",
    "semana": 8,
    "titulo": "Estratégia de Alternativas + Tabelas Complexas",
    "disciplinaNome": "Português + Matemática",
    "arquivo": "apostilas/dia-053.html",
    "funcaoPedagogica": "conteudo_aplicado",
    "tempoMeta": "60 a 90 min",
    "observacao": "Coerência e alternativas",
    "prioridadeAprovacao": "alta"
  },
  {
    "numero": 54,
    "data": "2026-05-15",
    "diaSemana": "sexta-feira",
    "semana": 8,
    "titulo": "Revisão da Semana 8 + Escolha Estratégica",
    "disciplinaNome": "Português + Matemática",
    "arquivo": "apostilas/dia-054.html",
    "funcaoPedagogica": "checkpoint_semanal",
    "tempoMeta": "60 a 90 min",
    "observacao": "Coerência e alternativas",
    "prioridadeAprovacao": "alta"
  },
  {
    "numero": 55,
    "data": "2026-05-16",
    "diaSemana": "sábado",
    "semana": 8,
    "titulo": "Simuladinho 8 — Eliminação de Alternativas",
    "disciplinaNome": "Simulado Semanal",
    "arquivo": "apostilas/dia-055.html",
    "funcaoPedagogica": "simulado_semanal",
    "tempoMeta": "35 a 40 min",
    "observacao": "Coerência e alternativas",
    "prioridadeAprovacao": "alta"
  },
  {
    "numero": 56,
    "data": "2026-05-17",
    "diaSemana": "domingo",
    "semana": 8,
    "titulo": "Folga / Recuperação Leve",
    "disciplinaNome": "Descanso",
    "arquivo": null,
    "funcaoPedagogica": "folga",
    "tempoMeta": "Folga",
    "observacao": "Domingo sem apostila. Descanso, leitura leve ou recuperação opcional do caderno de erros.",
    "prioridadeAprovacao": "alta"
  },
  {
    "numero": 57,
    "data": "2026-05-18",
    "diaSemana": "segunda-feira",
    "semana": 9,
    "titulo": "Efeito de Sentido + Porcentagem em Problemas",
    "disciplinaNome": "Português + Matemática",
    "arquivo": "apostilas/dia-057.html",
    "funcaoPedagogica": "conteudo_novo",
    "tempoMeta": "60 a 90 min",
    "observacao": "Pegadinhas reais",
    "prioridadeAprovacao": "alta"
  },
  {
    "numero": 58,
    "data": "2026-05-19",
    "diaSemana": "terça-feira",
    "semana": 9,
    "titulo": "Texto Verbal e Não Verbal + Unidades de Tempo",
    "disciplinaNome": "Português + Matemática",
    "arquivo": "apostilas/dia-058.html",
    "funcaoPedagogica": "conteudo_novo_com_revisao_24h",
    "tempoMeta": "60 a 90 min",
    "observacao": "Pegadinhas reais",
    "prioridadeAprovacao": "alta"
  },
  {
    "numero": 59,
    "data": "2026-05-20",
    "diaSemana": "quarta-feira",
    "semana": 9,
    "titulo": "Pegadinhas de Leitura + Medidas e Conversões",
    "disciplinaNome": "Português + Matemática",
    "arquivo": "apostilas/dia-059.html",
    "funcaoPedagogica": "conteudo_novo_com_revisao_24h",
    "tempoMeta": "60 a 90 min",
    "observacao": "Pegadinhas reais",
    "prioridadeAprovacao": "alta"
  },
  {
    "numero": 60,
    "data": "2026-05-21",
    "diaSemana": "quinta-feira",
    "semana": 9,
    "titulo": "Alternativa Correta sem Chute + Geometria Aplicada",
    "disciplinaNome": "Português + Matemática",
    "arquivo": "apostilas/dia-060.html",
    "funcaoPedagogica": "conteudo_aplicado",
    "tempoMeta": "60 a 90 min",
    "observacao": "Pegadinhas reais",
    "prioridadeAprovacao": "alta"
  },
  {
    "numero": 61,
    "data": "2026-05-22",
    "diaSemana": "sexta-feira",
    "semana": 9,
    "titulo": "Revisão da Semana 9 + Pressão Controlada",
    "disciplinaNome": "Português + Matemática",
    "arquivo": "apostilas/dia-061.html",
    "funcaoPedagogica": "checkpoint_semanal",
    "tempoMeta": "60 a 90 min",
    "observacao": "Pegadinhas reais",
    "prioridadeAprovacao": "alta"
  },
  {
    "numero": 62,
    "data": "2026-05-23",
    "diaSemana": "sábado",
    "semana": 9,
    "titulo": "Simuladinho 9 — Pressão e Detalhe",
    "disciplinaNome": "Simulado Semanal",
    "arquivo": "apostilas/dia-062.html",
    "funcaoPedagogica": "simulado_semanal",
    "tempoMeta": "35 a 40 min",
    "observacao": "Pegadinhas reais",
    "prioridadeAprovacao": "alta"
  },
  {
    "numero": 63,
    "data": "2026-05-24",
    "diaSemana": "domingo",
    "semana": 9,
    "titulo": "Folga / Recuperação Leve",
    "disciplinaNome": "Descanso",
    "arquivo": null,
    "funcaoPedagogica": "folga",
    "tempoMeta": "Folga",
    "observacao": "Domingo sem apostila. Descanso, leitura leve ou recuperação opcional do caderno de erros.",
    "prioridadeAprovacao": "alta"
  },
  {
    "numero": 64,
    "data": "2026-05-25",
    "diaSemana": "segunda-feira",
    "semana": 10,
    "titulo": "Mini Simulado 1 — Bloco A",
    "disciplinaNome": "Simulado Semanal",
    "arquivo": "apostilas/dia-064.html",
    "funcaoPedagogica": "simulado_semanal",
    "tempoMeta": "45 a 60 min",
    "observacao": "Mini simulado 1",
    "prioridadeAprovacao": "alta"
  },
  {
    "numero": 65,
    "data": "2026-05-26",
    "diaSemana": "terça-feira",
    "semana": 10,
    "titulo": "Correção Guiada do Simulado 1",
    "disciplinaNome": "Correção Estratégica",
    "arquivo": "apostilas/dia-065.html",
    "funcaoPedagogica": "simulado_semanal",
    "tempoMeta": "45 a 60 min",
    "observacao": "Mini simulado 1",
    "prioridadeAprovacao": "alta"
  },
  {
    "numero": 66,
    "data": "2026-05-27",
    "diaSemana": "quarta-feira",
    "semana": 10,
    "titulo": "Reensino dos Erros Prioritários",
    "disciplinaNome": "Correção Estratégica",
    "arquivo": "apostilas/dia-066.html",
    "funcaoPedagogica": "correcao_estrategica",
    "tempoMeta": "60 a 90 min",
    "observacao": "Mini simulado 1",
    "prioridadeAprovacao": "alta"
  },
  {
    "numero": 67,
    "data": "2026-05-28",
    "diaSemana": "quinta-feira",
    "semana": 10,
    "titulo": "Mini Simulado 1 — Bloco B",
    "disciplinaNome": "Simulado Semanal",
    "arquivo": "apostilas/dia-067.html",
    "funcaoPedagogica": "simulado_semanal",
    "tempoMeta": "45 a 60 min",
    "observacao": "Mini simulado 1",
    "prioridadeAprovacao": "alta"
  },
  {
    "numero": 68,
    "data": "2026-05-29",
    "diaSemana": "sexta-feira",
    "semana": 10,
    "titulo": "Consolidação Pós-Simulado 1",
    "disciplinaNome": "Simulado Semanal",
    "arquivo": "apostilas/dia-068.html",
    "funcaoPedagogica": "simulado_semanal",
    "tempoMeta": "45 a 60 min",
    "observacao": "Mini simulado 1",
    "prioridadeAprovacao": "alta"
  },
  {
    "numero": 69,
    "data": "2026-05-30",
    "diaSemana": "sábado",
    "semana": 10,
    "titulo": "Simuladinho 10 — Consolidação sob Tempo",
    "disciplinaNome": "Simulado Semanal",
    "arquivo": "apostilas/dia-069.html",
    "funcaoPedagogica": "simulado_semanal",
    "tempoMeta": "45 a 60 min",
    "observacao": "Mini simulado 1",
    "prioridadeAprovacao": "alta"
  },
  {
    "numero": 70,
    "data": "2026-05-31",
    "diaSemana": "domingo",
    "semana": 10,
    "titulo": "Folga / Recuperação Leve",
    "disciplinaNome": "Descanso",
    "arquivo": null,
    "funcaoPedagogica": "folga",
    "tempoMeta": "Folga",
    "observacao": "Domingo sem apostila. Descanso, leitura leve ou recuperação opcional do caderno de erros.",
    "prioridadeAprovacao": "alta"
  },
  {
    "numero": 71,
    "data": "2026-06-01",
    "diaSemana": "segunda-feira",
    "semana": 11,
    "titulo": "Mini Simulado 2 — Bloco A",
    "disciplinaNome": "Simulado Semanal",
    "arquivo": "apostilas/dia-071.html",
    "funcaoPedagogica": "simulado_semanal",
    "tempoMeta": "45 a 60 min",
    "observacao": "Mini simulado 2",
    "prioridadeAprovacao": "alta"
  },
  {
    "numero": 72,
    "data": "2026-06-02",
    "diaSemana": "terça-feira",
    "semana": 11,
    "titulo": "Correção com Estratégia de Prova",
    "disciplinaNome": "Correção Estratégica",
    "arquivo": "apostilas/dia-072.html",
    "funcaoPedagogica": "correcao_estrategica",
    "tempoMeta": "60 a 90 min",
    "observacao": "Mini simulado 2",
    "prioridadeAprovacao": "alta"
  },
  {
    "numero": 73,
    "data": "2026-06-03",
    "diaSemana": "quarta-feira",
    "semana": 11,
    "titulo": "Reforço dos Erros Recorrentes",
    "disciplinaNome": "Português + Matemática",
    "arquivo": "apostilas/dia-073.html",
    "funcaoPedagogica": "conteudo_novo_com_revisao_24h",
    "tempoMeta": "60 a 90 min",
    "observacao": "Mini simulado 2",
    "prioridadeAprovacao": "alta"
  },
  {
    "numero": 74,
    "data": "2026-06-04",
    "diaSemana": "quinta-feira",
    "semana": 11,
    "titulo": "Mini Simulado 2 — Bloco B",
    "disciplinaNome": "Simulado Semanal",
    "arquivo": "apostilas/dia-074.html",
    "funcaoPedagogica": "simulado_semanal",
    "tempoMeta": "45 a 60 min",
    "observacao": "Mini simulado 2",
    "prioridadeAprovacao": "alta"
  },
  {
    "numero": 75,
    "data": "2026-06-05",
    "diaSemana": "sexta-feira",
    "semana": 11,
    "titulo": "Checklist de Estabilidade",
    "disciplinaNome": "Correção Estratégica",
    "arquivo": "apostilas/dia-075.html",
    "funcaoPedagogica": "correcao_estrategica",
    "tempoMeta": "60 a 90 min",
    "observacao": "Mini simulado 2",
    "prioridadeAprovacao": "alta"
  },
  {
    "numero": 76,
    "data": "2026-06-06",
    "diaSemana": "sábado",
    "semana": 11,
    "titulo": "Simuladinho 11 — Estabilização",
    "disciplinaNome": "Simulado Semanal",
    "arquivo": "apostilas/dia-076.html",
    "funcaoPedagogica": "simulado_semanal",
    "tempoMeta": "45 a 60 min",
    "observacao": "Mini simulado 2",
    "prioridadeAprovacao": "alta"
  },
  {
    "numero": 77,
    "data": "2026-06-07",
    "diaSemana": "domingo",
    "semana": 11,
    "titulo": "Folga / Recuperação Leve",
    "disciplinaNome": "Descanso",
    "arquivo": null,
    "funcaoPedagogica": "folga",
    "tempoMeta": "Folga",
    "observacao": "Domingo sem apostila. Descanso, leitura leve ou recuperação opcional do caderno de erros.",
    "prioridadeAprovacao": "alta"
  },
  {
    "numero": 78,
    "data": "2026-06-08",
    "diaSemana": "segunda-feira",
    "semana": 12,
    "titulo": "Prova sob Pressão — Ritmo e Atenção",
    "disciplinaNome": "Português + Matemática",
    "arquivo": "apostilas/dia-078.html",
    "funcaoPedagogica": "conteudo_novo",
    "tempoMeta": "60 a 90 min",
    "observacao": "Tempo e estratégia",
    "prioridadeAprovacao": "alta"
  },
  {
    "numero": 79,
    "data": "2026-06-09",
    "diaSemana": "terça-feira",
    "semana": 12,
    "titulo": "Correção de Erros Recorrentes",
    "disciplinaNome": "Correção Estratégica",
    "arquivo": "apostilas/dia-079.html",
    "funcaoPedagogica": "correcao_estrategica",
    "tempoMeta": "60 a 90 min",
    "observacao": "Tempo e estratégia",
    "prioridadeAprovacao": "alta"
  },
  {
    "numero": 80,
    "data": "2026-06-10",
    "diaSemana": "quarta-feira",
    "semana": 12,
    "titulo": "Prova sob Pressão — Bloco Final",
    "disciplinaNome": "Português + Matemática",
    "arquivo": "apostilas/dia-080.html",
    "funcaoPedagogica": "conteudo_novo_com_revisao_24h",
    "tempoMeta": "60 a 90 min",
    "observacao": "Tempo e estratégia",
    "prioridadeAprovacao": "alta"
  },
  {
    "numero": 81,
    "data": "2026-06-11",
    "diaSemana": "quinta-feira",
    "semana": 12,
    "titulo": "Treino de Tempo + Marcação Inteligente",
    "disciplinaNome": "Português + Matemática",
    "arquivo": "apostilas/dia-081.html",
    "funcaoPedagogica": "conteudo_aplicado",
    "tempoMeta": "60 a 90 min",
    "observacao": "Tempo e estratégia",
    "prioridadeAprovacao": "alta"
  },
  {
    "numero": 82,
    "data": "2026-06-12",
    "diaSemana": "sexta-feira",
    "semana": 12,
    "titulo": "Protocolo Pessoal de Prova",
    "disciplinaNome": "Correção Estratégica",
    "arquivo": "apostilas/dia-082.html",
    "funcaoPedagogica": "correcao_estrategica",
    "tempoMeta": "60 a 90 min",
    "observacao": "Tempo e estratégia",
    "prioridadeAprovacao": "alta"
  },
  {
    "numero": 83,
    "data": "2026-06-13",
    "diaSemana": "sábado",
    "semana": 12,
    "titulo": "Simuladinho 12 — Ritmo e Estratégia",
    "disciplinaNome": "Simulado Semanal",
    "arquivo": "apostilas/dia-083.html",
    "funcaoPedagogica": "simulado_semanal",
    "tempoMeta": "45 a 60 min",
    "observacao": "Tempo e estratégia",
    "prioridadeAprovacao": "alta"
  },
  {
    "numero": 84,
    "data": "2026-06-14",
    "diaSemana": "domingo",
    "semana": 12,
    "titulo": "Folga / Recuperação Leve",
    "disciplinaNome": "Descanso",
    "arquivo": null,
    "funcaoPedagogica": "folga",
    "tempoMeta": "Folga",
    "observacao": "Domingo sem apostila. Descanso, leitura leve ou recuperação opcional do caderno de erros.",
    "prioridadeAprovacao": "alta"
  },
  {
    "numero": 85,
    "data": "2026-06-15",
    "diaSemana": "segunda-feira",
    "semana": 13,
    "titulo": "Revisão de Português que Mais Cai",
    "disciplinaNome": "Português",
    "arquivo": "apostilas/dia-085.html",
    "funcaoPedagogica": "conteudo_novo",
    "tempoMeta": "45 a 60 min",
    "observacao": "Revisão baseada em erro",
    "prioridadeAprovacao": "alta"
  },
  {
    "numero": 86,
    "data": "2026-06-16",
    "diaSemana": "terça-feira",
    "semana": 13,
    "titulo": "Revisão de Matemática que Mais Cai",
    "disciplinaNome": "Matemática",
    "arquivo": "apostilas/dia-086.html",
    "funcaoPedagogica": "conteudo_novo_com_revisao_24h",
    "tempoMeta": "45 a 60 min",
    "observacao": "Revisão baseada em erro",
    "prioridadeAprovacao": "alta"
  },
  {
    "numero": 87,
    "data": "2026-06-17",
    "diaSemana": "quarta-feira",
    "semana": 13,
    "titulo": "Lista Mista de Alta Prioridade",
    "disciplinaNome": "Português + Matemática",
    "arquivo": "apostilas/dia-087.html",
    "funcaoPedagogica": "conteudo_novo_com_revisao_24h",
    "tempoMeta": "60 a 90 min",
    "observacao": "Revisão baseada em erro",
    "prioridadeAprovacao": "alta"
  },
  {
    "numero": 88,
    "data": "2026-06-18",
    "diaSemana": "quinta-feira",
    "semana": 13,
    "titulo": "Correção Comentada dos Erros Mais Frequentes",
    "disciplinaNome": "Correção Estratégica",
    "arquivo": "apostilas/dia-088.html",
    "funcaoPedagogica": "correcao_estrategica",
    "tempoMeta": "60 a 90 min",
    "observacao": "Revisão baseada em erro",
    "prioridadeAprovacao": "alta"
  },
  {
    "numero": 89,
    "data": "2026-06-19",
    "diaSemana": "sexta-feira",
    "semana": 13,
    "titulo": "Revisão da Semana 13 + Foco Final",
    "disciplinaNome": "Português + Matemática",
    "arquivo": "apostilas/dia-089.html",
    "funcaoPedagogica": "checkpoint_semanal",
    "tempoMeta": "60 a 90 min",
    "observacao": "Revisão baseada em erro",
    "prioridadeAprovacao": "alta"
  },
  {
    "numero": 90,
    "data": "2026-06-20",
    "diaSemana": "sábado",
    "semana": 13,
    "titulo": "Simuladinho 13 — Revisão Cirúrgica",
    "disciplinaNome": "Simulado Semanal",
    "arquivo": "apostilas/dia-090.html",
    "funcaoPedagogica": "simulado_semanal",
    "tempoMeta": "25 a 35 min",
    "observacao": "Revisão baseada em erro",
    "prioridadeAprovacao": "alta"
  },
  {
    "numero": 91,
    "data": "2026-06-21",
    "diaSemana": "domingo",
    "semana": 13,
    "titulo": "Folga / Recuperação Leve",
    "disciplinaNome": "Descanso",
    "arquivo": null,
    "funcaoPedagogica": "folga",
    "tempoMeta": "Folga",
    "observacao": "Domingo sem apostila. Descanso, leitura leve ou recuperação opcional do caderno de erros.",
    "prioridadeAprovacao": "alta"
  },
  {
    "numero": 92,
    "data": "2026-06-22",
    "diaSemana": "segunda-feira",
    "semana": 14,
    "titulo": "Sprint Final — Leitura e Atenção",
    "disciplinaNome": "Sprint Final",
    "arquivo": "apostilas/dia-092.html",
    "funcaoPedagogica": "conteudo_novo",
    "tempoMeta": "45 a 60 min",
    "observacao": "Lapidação final",
    "prioridadeAprovacao": "alta"
  },
  {
    "numero": 93,
    "data": "2026-06-23",
    "diaSemana": "terça-feira",
    "semana": 14,
    "titulo": "Sprint Final — Cálculo e Precisão",
    "disciplinaNome": "Sprint Final",
    "arquivo": "apostilas/dia-093.html",
    "funcaoPedagogica": "conteudo_novo_com_revisao_24h",
    "tempoMeta": "45 a 60 min",
    "observacao": "Lapidação final",
    "prioridadeAprovacao": "alta"
  },
  {
    "numero": 94,
    "data": "2026-06-24",
    "diaSemana": "quarta-feira",
    "semana": 14,
    "titulo": "Sprint Final — Simulado Curto",
    "disciplinaNome": "Sprint Final",
    "arquivo": "apostilas/dia-094.html",
    "funcaoPedagogica": "simulado_semanal",
    "tempoMeta": "25 a 35 min",
    "observacao": "Lapidação final",
    "prioridadeAprovacao": "alta"
  },
  {
    "numero": 95,
    "data": "2026-06-25",
    "diaSemana": "quinta-feira",
    "semana": 14,
    "titulo": "Sprint Final — Correção e Confiança",
    "disciplinaNome": "Sprint Final",
    "arquivo": "apostilas/dia-095.html",
    "funcaoPedagogica": "conteudo_aplicado",
    "tempoMeta": "45 a 60 min",
    "observacao": "Lapidação final",
    "prioridadeAprovacao": "alta"
  },
  {
    "numero": 96,
    "data": "2026-06-26",
    "diaSemana": "sexta-feira",
    "semana": 14,
    "titulo": "Véspera Inteligente + Revisão Final",
    "disciplinaNome": "Sprint Final",
    "arquivo": "apostilas/dia-096.html",
    "funcaoPedagogica": "checkpoint_semanal",
    "tempoMeta": "45 a 60 min",
    "observacao": "Lapidação final",
    "prioridadeAprovacao": "alta"
  },
  {
    "numero": 97,
    "data": "2026-06-27",
    "diaSemana": "sábado",
    "semana": 14,
    "titulo": "Simulado 14 — Encerramento Leve",
    "disciplinaNome": "Simulado Semanal",
    "arquivo": "apostilas/dia-097.html",
    "funcaoPedagogica": "simulado_semanal",
    "tempoMeta": "25 a 35 min",
    "observacao": "Lapidação final",
    "prioridadeAprovacao": "alta"
  }
];


window.CONFIG = { projeto, fases, semanas, dias };

window.getDiaPorData = function(dateISO) {
  return (window.CONFIG.dias || []).find(d => d.data === dateISO) || null;
};

window.getDiaPorNumero = function(numero) {
  return (window.CONFIG.dias || []).find(d => d.numero === numero) || null;
};

window.getRecompensaDaSemana = function(semana) {
  return (window.CONFIG.semanas || []).find(w => w.semana === semana) || null;
};
